// Mock data for the R&D surface during the UI-building phase. When the backend
// phase starts, a getter layer replaces the import sites — these mocks stay as
// fixtures. Every cross-referenced id (insights, problem reports, milestones,
// team members) resolves within this file.

import type {
  MarketInsight,
  OpenRole,
  ProblemReport,
  ProjectStage,
  ResearchProject,
  TalentProfile,
  TrendingSignal,
} from "@/types/research-and-development";

export const PROJECT_STAGE_LABELS: Record<ProjectStage, string> = {
  "market-research": "Market Research",
  "problem-validation": "Problem Validation",
  "team-building": "Team Building",
  "building-mvp": "Building MVP",
  "raising-funding": "Raising Funding",
  "go-to-market": "Go-to-Market",
};

export const MOCK_MARKET_INSIGHTS: MarketInsight[] = [
  {
    id: "insight-cold-storage-demand",
    headline: "Demand for off-grid cold storage is up 34% year over year in East Africa",
    statValue: "+34%",
    trendDirection: "up",
    region: "East Africa",
    category: "Cold Chain",
    sourceNote: "Qatoto demand index, Jun 2026",
  },
  {
    id: "insight-water-access-gap",
    headline:
      "68 million people in South Asia draw from groundwater flagged for arsenic contamination",
    statValue: "68M people",
    trendDirection: "up",
    region: "South Asia",
    category: "Water & Sanitation",
    sourceNote: "WHO regional water survey, 2025",
  },
  {
    id: "insight-drone-agriculture-growth",
    headline: "Smallholder drone-scouting service bookings in Latin America doubled in 18 months",
    statValue: "+112%",
    trendDirection: "up",
    region: "Latin America",
    category: "Precision Agriculture",
    sourceNote: "Regional agri-service marketplace data, May 2026",
  },
  {
    id: "insight-prefab-construction-surge",
    headline: "Post-typhoon rebuild programs list prefab wall panels as their top procurement gap",
    statValue: "+41%",
    trendDirection: "up",
    region: "Southeast Asia",
    category: "Modular Construction",
    sourceNote: "Philippine housing authority tenders, Q1 2026",
  },
  {
    id: "insight-e-waste-volume",
    headline: "West Africa receives an estimated 250,000 tonnes of untracked e-waste each year",
    statValue: "250K tonnes",
    trendDirection: "up",
    region: "West Africa",
    category: "E-Waste & Recycling",
    sourceNote: "Basel Convention shipment estimates, 2025",
  },
  {
    id: "insight-pharma-logistics-compliance",
    headline:
      "New EU rules require validated cold-chain packaging on three times more pharma shipment classes",
    statValue: "3× coverage",
    trendDirection: "up",
    region: "Europe",
    category: "Medical Logistics",
    sourceNote: "EU GDP directive amendment, Mar 2026",
  },
  {
    id: "insight-solar-hardware-costs",
    headline:
      "Off-grid solar component costs have fallen 22% since 2024, widening rural hardware margins",
    statValue: "-22%",
    trendDirection: "down",
    region: "Global",
    category: "Off-Grid Solar",
    sourceNote: "Distributor price index, Jun 2026",
  },
  {
    id: "insight-smallholder-financing",
    headline: "Smallholder equipment-financing approval rates have plateaued near 31%",
    statValue: "31%",
    trendDirection: "flat",
    region: "East Africa",
    category: "Smallholder Finance",
    sourceNote: "Agri-lender consortium report, Apr 2026",
  },
];

export const MOCK_PROBLEM_REPORTS: ProblemReport[] = [
  {
    id: "report-produce-spoilage-nakuru",
    title: "Fresh produce spoils before reaching Nairobi markets",
    category: "Cold Chain",
    locationLabel: "Nakuru County, Kenya",
    countryCode: "KE",
    mapPosition: { leftPercent: 58, topPercent: 55 },
    reportCount: 342,
    opportunityScore: 91,
    description:
      "Vendors report losing up to a third of tomatoes and leafy greens in transit because no affordable cold storage exists between farm-gate aggregation points and the city wholesale market.",
    reportedDate: "May 12, 2026",
  },
  {
    id: "report-clinic-vaccine-storage-mwanza",
    title: "Rural clinics lose vaccine stock during grid outages",
    category: "Healthcare",
    locationLabel: "Mwanza, Tanzania",
    countryCode: "TZ",
    mapPosition: { leftPercent: 59, topPercent: 58 },
    reportCount: 187,
    opportunityScore: 84,
    description:
      "Health workers describe discarding entire vaccine batches after multi-day power cuts; backup generators are shared across facilities and rarely reach the outlying dispensaries in time.",
    reportedDate: "Jun 2, 2026",
  },
  {
    id: "report-arsenic-groundwater-khulna",
    title: "Tube wells test above arsenic safety limits",
    category: "Water & Sanitation",
    locationLabel: "Khulna Division, Bangladesh",
    countryCode: "BD",
    mapPosition: { leftPercent: 69, topPercent: 47 },
    reportCount: 428,
    opportunityScore: 93,
    description:
      "Community testing drives keep flagging shallow tube wells above national arsenic limits, but households have no affordable point-of-use treatment and keep drinking from the marked wells.",
    reportedDate: "Apr 28, 2026",
  },
  {
    id: "report-crop-monitoring-cost-cusco",
    title: "Crop-health scouting is unaffordable for terraced smallholdings",
    category: "Precision Agriculture",
    locationLabel: "Cusco Region, Peru",
    countryCode: "PE",
    mapPosition: { leftPercent: 31, topPercent: 63 },
    reportCount: 156,
    opportunityScore: 72,
    description:
      "Imported drone-scouting services quote per-hectare rates designed for flat industrial farms; terraced plots under two hectares are quoted at triple the price or refused outright.",
    reportedDate: "May 30, 2026",
  },
  {
    id: "report-coffee-frost-losses-minas",
    title: "Frost damage on coffee farms goes undetected until harvest",
    category: "Precision Agriculture",
    locationLabel: "Minas Gerais, Brazil",
    countryCode: "BR",
    mapPosition: { leftPercent: 36, topPercent: 64 },
    reportCount: 203,
    opportunityScore: 77,
    description:
      "Growers only discover the extent of frost burn at picking time, months after intervention could have saved part of the crop; affordable canopy-level imaging simply is not on offer.",
    reportedDate: "Jun 15, 2026",
  },
  {
    id: "report-typhoon-housing-backlog-tacloban",
    title: "Typhoon rebuild queue exceeds three years for displaced families",
    category: "Housing",
    locationLabel: "Tacloban, Philippines",
    countryCode: "PH",
    mapPosition: { leftPercent: 75, topPercent: 53 },
    reportCount: 512,
    opportunityScore: 95,
    description:
      "Families displaced by the last two typhoon seasons remain in transitional shelters because conventional concrete-block construction cannot keep pace with the government rebuild backlog.",
    reportedDate: "Mar 19, 2026",
  },
  {
    id: "report-informal-e-waste-burning-accra",
    title: "Open burning of imported e-waste at Agbogbloshie",
    category: "E-Waste & Recycling",
    locationLabel: "Accra, Ghana",
    countryCode: "GH",
    mapPosition: { leftPercent: 46, topPercent: 53 },
    reportCount: 389,
    opportunityScore: 89,
    description:
      "Informal workers burn cable insulation and circuit boards to recover copper, releasing dioxins near residential areas; no formal recovery facility pays competitive scrap prices.",
    reportedDate: "Feb 24, 2026",
  },
  {
    id: "report-cold-chain-audit-failures-lyon",
    title: "Specialty pharma couriers fail temperature audits on last-mile legs",
    category: "Medical Logistics",
    locationLabel: "Lyon, France",
    countryCode: "FR",
    mapPosition: { leftPercent: 49, topPercent: 33 },
    reportCount: 98,
    opportunityScore: 68,
    description:
      "Regional couriers report recurring excursions above 8°C on final-hour deliveries of biologics; single-use gel-pack shippers cannot bridge summer heat waves in delivery vans.",
    reportedDate: "Jun 21, 2026",
  },
];

export const MOCK_RESEARCH_PROJECTS: ResearchProject[] = [
  {
    id: "solar-cold-storage",
    name: "SolarChill Cold Storage",
    tagline: "Solar-powered walk-in cold rooms for smallholder produce markets in East Africa.",
    description:
      "SolarChill builds pay-per-crate cold rooms at produce aggregation points between Nakuru farms and Nairobi wholesale markets. Each unit pairs locally serviceable vapor-compression refrigeration with an oversized solar array and thermal storage, so vendors keep produce fresh through multi-day grid outages without diesel. The team is currently sizing demand: how many crates per market, at what price per night, and which cooperatives will anchor the first three sites.",
    category: "Cold Chain",
    stage: "market-research",
    coverImageSrc: "/dummy/rnd_project_cover_01.avif",
    founderId: "wanjiru-kamau",
    teamMembers: [
      {
        id: "wanjiru-kamau",
        name: "Wanjiru Kamau",
        avatarImageSrc: "/dummy/profile_image_01.avif",
        role: "Founder & Product Lead",
        skills: ["Agricultural supply chains", "Field research", "Partnership development"],
        equityShare: "62%",
        effortHoursLogged: 148,
        joinedDate: "Apr 6, 2026",
        isFounder: true,
      },
      {
        id: "daniel-otieno",
        name: "Daniel Otieno",
        avatarImageSrc: "/dummy/profile_image_02.avif",
        role: "Refrigeration Engineer",
        skills: ["Vapor-compression systems", "Solar PV sizing", "CAD"],
        equityShare: "9%",
        effortHoursLogged: 96,
        joinedDate: "Apr 20, 2026",
      },
      {
        id: "grace-muthoni",
        name: "Grace Muthoni",
        avatarImageSrc: "/dummy/profile_image_03.avif",
        role: "Market Researcher",
        skills: ["Survey design", "Swahili-language interviews", "Data analysis"],
        equityShare: "5.5%",
        effortHoursLogged: 82,
        joinedDate: "May 4, 2026",
      },
      {
        id: "samuel-kiprop",
        name: "Samuel Kiprop",
        avatarImageSrc: "/dummy/profile_image_04.avif",
        role: "Field Operations",
        skills: ["Logistics", "Vendor relations"],
        equityShare: "4%",
        effortHoursLogged: 61,
        joinedDate: "May 18, 2026",
      },
    ],
    openRoles: [
      {
        id: "solar-role-cooling-systems-engineer",
        projectId: "solar-cold-storage",
        projectName: "SolarChill Cold Storage",
        roleTitle: "Cooling Systems Engineer",
        skills: ["Thermal modeling", "Off-grid power", "Prototyping"],
        equityRange: "3–6%",
        commitment: "full-time",
      },
    ],
    milestones: [
      {
        id: "solar-milestone-demand-survey",
        title: "Complete 400-vendor demand survey",
        description:
          "Structured interviews across four Nakuru-corridor markets on spoilage rates and willingness to pay per crate-night.",
        targetDate: "Jun 20, 2026",
        status: "done",
        escrowReleaseAmount: "$600",
      },
      {
        id: "solar-milestone-cost-model",
        title: "Publish landed-cost model per cold room",
        description:
          "Full bill of materials, import duties, and installation labor for one 20-crate unit, priced against diesel alternatives.",
        targetDate: "Jul 18, 2026",
        status: "current",
        escrowReleaseAmount: "$1,200",
      },
      {
        id: "solar-milestone-pilot-sites",
        title: "Sign letters of intent with 3 pilot market cooperatives",
        description:
          "Anchor cooperatives commit floor space and a minimum nightly crate volume for the first season.",
        targetDate: "Aug 22, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$1,500",
      },
      {
        id: "solar-milestone-prototype-spec",
        title: "Freeze v1 cold-room engineering spec",
        description:
          "Refrigeration loop, panel array, and thermal-storage sizing locked for the pilot build.",
        targetDate: "Sep 30, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$2,000",
      },
      {
        id: "solar-milestone-first-build",
        title: "Assemble first cold room at Nakuru pilot site",
        description: "On-site assembly, commissioning, and a two-week loaded temperature trial.",
        targetDate: "Nov 15, 2026",
        status: "upcoming",
      },
    ],
    dailyLogs: [
      {
        id: "solar-log-jul-7",
        authorId: "grace-muthoni",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image01.avif",
        transcriptExcerpt:
          "Closed out 46 more vendor interviews today at Wakulima market — that puts us at 312 of the 400 target, and the spoilage numbers keep landing between 28 and 35 percent.",
        detail:
          "The afternoon batch skewed toward leafy-green sellers, who report the worst overnight losses. Willingness to pay clusters around 25 shillings per crate-night, higher than our model assumed. Two vendors volunteered to be reference customers for the pilot.",
        aiSummaryChips: [
          { kind: "progress", label: "312 of 400 surveys complete" },
          { kind: "velocity", label: "Ahead of weekly interview target" },
        ],
        isEffortVerified: false,
      },
      {
        id: "solar-log-jul-6",
        authorId: "daniel-otieno",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image02.avif",
        transcriptExcerpt:
          "The compressor quote from the Nairobi distributor slipped another three weeks, which pushes the cost model — I spent the day pricing an alternative supplier in Mombasa.",
        detail:
          "The Mombasa supplier stocks a comparable R290 compressor at 8% higher unit cost but with two-week delivery and a local service agent. I drafted both options into the landed-cost spreadsheet so Wanjiru can decide before Friday.",
        aiSummaryChips: [
          { kind: "blocker", label: "Compressor quote delayed 3 weeks" },
          { kind: "suggestion", label: "Evaluate Mombasa supplier alternative" },
        ],
        isEffortVerified: true,
      },
      {
        id: "solar-log-jul-5",
        authorId: "wanjiru-kamau",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image03.avif",
        transcriptExcerpt:
          "Good day — the Nakuru West cooperative board agreed to a formal sit-down on the 15th, and they are bringing the two neighboring market committees with them.",
        detail:
          "If that meeting lands, all three pilot letters of intent could come from one negotiation. I also walked the proposed site behind the main market: level ground, existing security fencing, and a transformer within 40 meters if we ever want a grid tie.",
        aiSummaryChips: [{ kind: "progress", label: "Cooperative board meeting booked" }],
        isEffortVerified: true,
      },
      {
        id: "solar-log-jul-4",
        authorId: "samuel-kiprop",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image04.avif",
        transcriptExcerpt:
          "Finished the site shortlist two days early — five candidate locations scored on access roads, security, and distance to the aggregation sheds.",
        detail:
          "Nakuru West and Gilgil junction score highest. I logged drive times at market-day traffic, not off-peak, since that is when crates actually move. Recommend we drop the Naivasha site: the access road floods in the long rains.",
        aiSummaryChips: [
          { kind: "velocity", label: "Site shortlist done 2 days early" },
          { kind: "suggestion", label: "Drop flood-prone Naivasha site" },
        ],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "solar-round-community-preseed",
        type: "crowdfunding",
        goalAmount: "$6,000",
        raisedAmount: "$1,450",
        percentageFunded: 24,
        backersCount: 38,
        closesOnDate: "Aug 30, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "solar-escrow-5",
        date: "Jul 2, 2026",
        description: "Backer pledges — week of Jun 29",
        direction: "in",
        amount: "$450",
        verificationStatus: "pending",
      },
      {
        id: "solar-escrow-4",
        date: "Jun 28, 2026",
        description: "Backer pledges — week of Jun 22",
        direction: "in",
        amount: "$250",
        verificationStatus: "verified",
      },
      {
        id: "solar-escrow-3",
        date: "Jun 22, 2026",
        description: "Milestone release — 400-vendor demand survey",
        direction: "out",
        amount: "$600",
        linkedMilestoneId: "solar-milestone-demand-survey",
        verificationStatus: "verified",
      },
      {
        id: "solar-escrow-2",
        date: "Jun 14, 2026",
        description: "Backer pledges — week of Jun 8",
        direction: "in",
        amount: "$400",
        verificationStatus: "verified",
      },
      {
        id: "solar-escrow-1",
        date: "Jun 5, 2026",
        description: "Community round opening deposits",
        direction: "in",
        amount: "$350",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 214,
    dailyLogStreakDays: 12,
    originProblemReportId: "report-produce-spoilage-nakuru",
    relatedInsightIds: [
      "insight-cold-storage-demand",
      "insight-solar-hardware-costs",
      "insight-smallholder-financing",
    ],
  },
  {
    id: "modular-water-purification",
    name: "ClearFlow Modular Purification",
    tagline:
      "Stackable arsenic and pathogen filtration units for village water points in South Asia.",
    description:
      "ClearFlow designs a stackable filtration module that bolts onto existing tube wells and community water points, removing arsenic and biological contaminants without electricity. Modules share one molded housing so villages can add capacity as they grow, and spent filter media swaps out in minutes with no tools. The team is validating the problem household by household in Khulna Division before freezing the filter-media mix.",
    category: "Water & Sanitation",
    stage: "problem-validation",
    coverImageSrc: "/dummy/rnd_project_cover_02.avif",
    founderId: "farhana-rahman",
    teamMembers: [
      {
        id: "farhana-rahman",
        name: "Farhana Rahman",
        avatarImageSrc: "/dummy/profile_image_05.avif",
        role: "Founder & Water Engineer",
        skills: ["Filtration chemistry", "WASH programs", "Bengali-language fieldwork"],
        equityShare: "68%",
        effortHoursLogged: 176,
        joinedDate: "Mar 15, 2026",
        isFounder: true,
      },
      {
        id: "arjun-mehta",
        name: "Arjun Mehta",
        avatarImageSrc: "/dummy/profile_image_06.avif",
        role: "Hardware Designer",
        skills: ["Injection molding", "Design for manufacture", "CAD"],
        equityShare: "8%",
        effortHoursLogged: 104,
        joinedDate: "Apr 2, 2026",
      },
      {
        id: "nusrat-jahan",
        name: "Nusrat Jahan",
        avatarImageSrc: "/dummy/profile_image_07.avif",
        role: "Community Research Lead",
        skills: ["Household surveys", "NGO coordination"],
        equityShare: "6%",
        effortHoursLogged: 88,
        joinedDate: "Apr 10, 2026",
      },
    ],
    openRoles: [
      {
        id: "water-role-water-quality-chemist",
        projectId: "modular-water-purification",
        projectName: "ClearFlow Modular Purification",
        roleTitle: "Water Quality Chemist",
        skills: ["Lab assay design", "Arsenic speciation", "Field test kits"],
        equityRange: "2–4%",
        commitment: "part-time",
      },
    ],
    milestones: [
      {
        id: "water-milestone-contamination-mapping",
        title: "Map contamination levels across 40 tube wells",
        description:
          "Field assays across three unions in Khulna Division to size the affected population and contamination range.",
        targetDate: "Jun 10, 2026",
        status: "done",
        escrowReleaseAmount: "$1,100",
      },
      {
        id: "water-milestone-household-interviews",
        title: "Complete 120 household willingness-to-pay interviews",
        description:
          "Structured interviews on current water-fetching costs, health spending, and acceptable price per module.",
        targetDate: "Jul 21, 2026",
        status: "current",
        escrowReleaseAmount: "$1,400",
      },
      {
        id: "water-milestone-filter-media-selection",
        title: "Select filter media mix from lab candidates",
        description:
          "Bench comparison of iron-oxide and activated-alumina blends against the mapped contamination range.",
        targetDate: "Aug 25, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$1,800",
      },
      {
        id: "water-milestone-village-pilot",
        title: "Install pilot unit at Khulna village water point",
        description: "First full module in daily community use with weekly water-quality sampling.",
        targetDate: "Oct 8, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$2,600",
      },
      {
        id: "water-milestone-certification-plan",
        title: "File national drinking-water certification plan",
        description:
          "Certification pathway agreed with the national standards body, with required test schedule.",
        targetDate: "Nov 20, 2026",
        status: "upcoming",
      },
    ],
    dailyLogs: [
      {
        id: "water-log-jul-7",
        authorId: "nusrat-jahan",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image05.avif",
        transcriptExcerpt:
          "Interviewed 14 households in Dumuria today — 89 of 120 done. Families spend more on stomach-illness treatment than our module would cost them in a year.",
        detail:
          "The health-spending finding keeps repeating: an average of 340 taka a month on clinic visits and medicine attributed to water. That reframes the pitch from a purchase to a saving. Three households asked to join the pilot on the spot.",
        aiSummaryChips: [
          { kind: "progress", label: "89 of 120 interviews complete" },
          { kind: "velocity", label: "Interview pace up 20% this week" },
        ],
        isEffortVerified: true,
      },
      {
        id: "water-log-jul-6",
        authorId: "farhana-rahman",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image06.avif",
        transcriptExcerpt:
          "The arsenic speciation reagents are stuck at Chattogram customs — that stalls the lab comparison, so I reordered a smaller batch through the university lab's standing import license.",
        detail:
          "Worst case we lose ten days on the filter-media bench tests. The university route has cleared customs in under a week before, and Professor Karim agreed to receive the shipment. I also updated the milestone risk notes for backers.",
        aiSummaryChips: [
          { kind: "blocker", label: "Reagent shipment held at customs" },
          { kind: "suggestion", label: "Route imports via university license" },
        ],
        isEffortVerified: true,
      },
      {
        id: "water-log-jul-5",
        authorId: "arjun-mehta",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image07.avif",
        transcriptExcerpt:
          "Revised the housing tooling for a single-cavity mold first — cuts our initial tooling cost by more than half while we are still iterating on wall thickness.",
        detail:
          "The two-cavity mold only pays off past 5,000 units a year, and we will not see that volume before certification. Single-cavity keeps the same part geometry, so nothing downstream changes. Sent the revised quote request to both toolmakers.",
        aiSummaryChips: [{ kind: "progress", label: "Tooling cost cut by half" }],
        isEffortVerified: true,
      },
      {
        id: "water-log-jul-4",
        authorId: "farhana-rahman",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image08.avif",
        transcriptExcerpt:
          "Met the BRAC WASH coordinator for Khulna — they want quarterly water-quality data from the pilot and in exchange will introduce us to eleven more village committees.",
        detail:
          "That introduction pipeline is bigger than anything we could build ourselves this year. The data-sharing ask is easy since we planned weekly sampling anyway. Drafted a one-page memorandum for their regional office to review.",
        aiSummaryChips: [
          { kind: "progress", label: "BRAC partnership memorandum drafted" },
          { kind: "suggestion", label: "Publish pilot water data quarterly" },
        ],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "water-round-community",
        type: "crowdfunding",
        goalAmount: "$15,000",
        raisedAmount: "$4,900",
        percentageFunded: 33,
        backersCount: 112,
        closesOnDate: "Sep 12, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "water-escrow-6",
        date: "Jul 5, 2026",
        description: "Backer pledges — week of Jun 29",
        direction: "in",
        amount: "$700",
        verificationStatus: "pending",
      },
      {
        id: "water-escrow-5",
        date: "Jun 26, 2026",
        description: "Backer pledges — week of Jun 22",
        direction: "in",
        amount: "$1,300",
        verificationStatus: "verified",
      },
      {
        id: "water-escrow-4",
        date: "Jun 14, 2026",
        description: "Milestone release — tube-well contamination mapping",
        direction: "out",
        amount: "$1,100",
        linkedMilestoneId: "water-milestone-contamination-mapping",
        verificationStatus: "verified",
      },
      {
        id: "water-escrow-3",
        date: "Jun 12, 2026",
        description: "Backer pledges — week of Jun 8",
        direction: "in",
        amount: "$1,100",
        verificationStatus: "verified",
      },
      {
        id: "water-escrow-2",
        date: "May 30, 2026",
        description: "Backer pledges — week of May 25",
        direction: "in",
        amount: "$1,000",
        verificationStatus: "verified",
      },
      {
        id: "water-escrow-1",
        date: "May 18, 2026",
        description: "Community round opening deposits",
        direction: "in",
        amount: "$800",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 156,
    dailyLogStreakDays: 7,
    relatedInsightIds: ["insight-water-access-gap", "insight-solar-hardware-costs"],
  },
  {
    id: "agricultural-drone-kits",
    name: "AgriFly Drone Kits",
    tagline: "Affordable crop-scouting drone kits assembled and serviced locally across the Andes.",
    description:
      "AgriFly packages a crop-scouting drone as a kit: composite airframe, open flight firmware, and a multispectral camera tuned for terraced smallholdings that imported services refuse to fly. Kits are assembled and repaired by local technicians, keeping the service price within reach of farms under two hectares. The reference design has flown; the team is now hiring the pilots and supply-chain hands to run the first ten-farm trial.",
    category: "Precision Agriculture",
    stage: "team-building",
    coverImageSrc: "/dummy/rnd_project_cover_03.avif",
    founderId: "mateo-villanueva",
    teamMembers: [
      {
        id: "mateo-villanueva",
        name: "Mateo Villanueva",
        avatarImageSrc: "/dummy/profile_image_08.avif",
        role: "Founder & Aeronautics Engineer",
        skills: ["Flight-control firmware", "Composite airframes", "Agronomy basics"],
        equityShare: "58%",
        effortHoursLogged: 232,
        joinedDate: "Feb 9, 2026",
        isFounder: true,
      },
      {
        id: "camila-rojas",
        name: "Camila Rojas",
        avatarImageSrc: "/dummy/profile_image_09.avif",
        role: "Agronomy Lead",
        skills: ["Crop pathology", "NDVI interpretation", "Farmer training"],
        equityShare: "10%",
        effortHoursLogged: 141,
        joinedDate: "Mar 3, 2026",
      },
      {
        id: "diego-fernandez",
        name: "Diego Fernández",
        avatarImageSrc: "/dummy/profile_image_10.avif",
        role: "Embedded Engineer",
        skills: ["C++", "Sensor fusion", "PCB bring-up"],
        equityShare: "8%",
        effortHoursLogged: 128,
        joinedDate: "Mar 21, 2026",
      },
      {
        id: "lucia-herrera",
        name: "Lucía Herrera",
        avatarImageSrc: "/dummy/profile_image_11.avif",
        role: "Community & Partnerships",
        skills: ["Cooperative outreach", "Spanish and Quechua interpretation"],
        equityShare: "5%",
        effortHoursLogged: 87,
        joinedDate: "Apr 14, 2026",
      },
    ],
    openRoles: [
      {
        id: "drone-role-flight-test-pilot",
        projectId: "agricultural-drone-kits",
        projectName: "AgriFly Drone Kits",
        roleTitle: "Flight Test Pilot",
        skills: ["UAV piloting", "Flight logging", "Safety procedures"],
        equityRange: "1.5–3%",
        commitment: "part-time",
      },
      {
        id: "drone-role-supply-chain-lead",
        projectId: "agricultural-drone-kits",
        projectName: "AgriFly Drone Kits",
        roleTitle: "Supply Chain Lead",
        skills: ["Component sourcing", "Import compliance", "Inventory planning"],
        equityRange: "3–5%",
        commitment: "full-time",
      },
      {
        id: "drone-role-firmware-contributor",
        projectId: "agricultural-drone-kits",
        projectName: "AgriFly Drone Kits",
        roleTitle: "Firmware Contributor",
        skills: ["Rust", "Embedded Linux", "MAVLink"],
        equityRange: "0.5–1.5%",
        commitment: "hobby",
      },
    ],
    milestones: [
      {
        id: "drone-milestone-reference-design",
        title: "Freeze reference airframe design",
        description:
          "Composite airframe geometry and motor layout locked after wind-tunnel-substitute rig tests.",
        targetDate: "May 2, 2026",
        status: "done",
        escrowReleaseAmount: "$2,200",
      },
      {
        id: "drone-milestone-first-flight",
        title: "Complete first instrumented test flight",
        description:
          "Full sensor payload flown over the test parcel with clean telemetry and imaging capture.",
        targetDate: "Jun 18, 2026",
        status: "done",
        escrowReleaseAmount: "$3,000",
      },
      {
        id: "drone-milestone-core-team",
        title: "Fill flight-test and supply-chain roles",
        description:
          "Two open roles signed with equity agreements so the field trial can be crewed.",
        targetDate: "Jul 25, 2026",
        status: "current",
        escrowReleaseAmount: "$1,600",
      },
      {
        id: "drone-milestone-field-trial",
        title: "Run 10-farm scouting trial in Cusco",
        description:
          "Weekly scouting flights over ten terraced smallholdings for a full month, with agronomy reports delivered.",
        targetDate: "Sep 5, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$4,500",
      },
      {
        id: "drone-milestone-assembly-manual",
        title: "Publish local assembly and repair manual",
        description:
          "Spanish-language build and maintenance documentation validated by two independent technicians.",
        targetDate: "Oct 17, 2026",
        status: "upcoming",
      },
    ],
    dailyLogs: [
      {
        id: "drone-log-jul-7",
        authorId: "diego-fernandez",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image09.avif",
        transcriptExcerpt:
          "Fixed the sensor-fusion drift that was skewing altitude hold above 3,500 meters — the barometer compensation table now covers Andean elevations properly.",
        detail:
          "The stock firmware assumed sea-level-ish operation and drifted badly in thin air. I rebuilt the compensation table from our Cusco test-flight telemetry and altitude hold now stays within half a meter. Pushed the fix upstream to the open firmware repo as well.",
        aiSummaryChips: [
          { kind: "progress", label: "High-altitude drift fixed" },
          { kind: "velocity", label: "Firmware milestone a week early" },
        ],
        isEffortVerified: true,
      },
      {
        id: "drone-log-jul-6",
        authorId: "mateo-villanueva",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image10.avif",
        transcriptExcerpt:
          "Motor mounts are backordered six weeks from the usual distributor. I had two candidate mounts machined locally today to test as substitutes.",
        detail:
          "A Cusco machine shop turned both variants around in a day at a third of the imported price. If they pass vibration testing this week, local machining becomes the default and the kit gets cheaper and easier to repair — which was the whole thesis anyway.",
        aiSummaryChips: [
          { kind: "blocker", label: "Motor mounts backordered 6 weeks" },
          { kind: "suggestion", label: "Qualify locally machined mounts" },
        ],
        isEffortVerified: true,
      },
      {
        id: "drone-log-jul-5",
        authorId: "camila-rojas",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image11.avif",
        transcriptExcerpt:
          "Finished the scouting report template with the cooperative's agronomist — one page per parcel, traffic-light crop stress zones, and a recommended action per zone.",
        detail:
          "Farmers in the focus group wanted actions, not imagery: spray here, irrigate there, wait elsewhere. The template leads with the recommendation and buries the NDVI maps in an appendix. Two cooperatives asked for sample reports for their next assembly.",
        aiSummaryChips: [{ kind: "progress", label: "Scouting report template validated" }],
        isEffortVerified: true,
      },
      {
        id: "drone-log-jul-4",
        authorId: "lucia-herrera",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image12.avif",
        transcriptExcerpt:
          "Held interviews for the flight-test pilot role — three strong candidates, including a licensed instructor from the aero club who already flies survey missions.",
        detail:
          "The instructor candidate can also train future technicians, which doubles the value of the hire. I proposed we weight training ability in the final decision. Reference calls booked for Wednesday; equity conversation drafted with Mateo.",
        aiSummaryChips: [
          { kind: "progress", label: "3 pilot candidates shortlisted" },
          { kind: "suggestion", label: "Weight training ability in hiring" },
        ],
        isEffortVerified: true,
      },
      {
        id: "drone-log-jul-3",
        authorId: "mateo-villanueva",
        date: "Jul 3, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image01.avif",
        transcriptExcerpt:
          "Batch-built three more airframes in a single day using the new layup jigs — build time per frame is down from nine hours to five and a half.",
        detail:
          "The jigs paid for themselves in one session. At this pace the trial fleet of six aircraft is done two weeks before the field trial starts, leaving margin for a crash spare. Logged the layup procedure on video for the assembly manual.",
        aiSummaryChips: [{ kind: "velocity", label: "Airframe build time down 40%" }],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "drone-round-seed-equity",
        type: "equity",
        goalAmount: "$40,000",
        raisedAmount: "$12,400",
        percentageFunded: 31,
        backersCount: 21,
        closesOnDate: "Oct 1, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "drone-escrow-6",
        date: "Jul 3, 2026",
        description: "Angel pledge — pending fund verification",
        direction: "in",
        amount: "$2,400",
        verificationStatus: "pending",
      },
      {
        id: "drone-escrow-5",
        date: "Jun 20, 2026",
        description: "Milestone release — first instrumented flight",
        direction: "out",
        amount: "$3,000",
        linkedMilestoneId: "drone-milestone-first-flight",
        verificationStatus: "verified",
      },
      {
        id: "drone-escrow-4",
        date: "Jun 19, 2026",
        description: "Backer deposits — June cohort",
        direction: "in",
        amount: "$3,500",
        verificationStatus: "verified",
      },
      {
        id: "drone-escrow-3",
        date: "Jun 2, 2026",
        description: "Backer deposits — late-May cohort",
        direction: "in",
        amount: "$2,800",
        verificationStatus: "verified",
      },
      {
        id: "drone-escrow-2",
        date: "May 9, 2026",
        description: "Milestone release — reference airframe design",
        direction: "out",
        amount: "$2,200",
        linkedMilestoneId: "drone-milestone-reference-design",
        verificationStatus: "verified",
      },
      {
        id: "drone-escrow-1",
        date: "May 6, 2026",
        description: "Seed round opening deposits",
        direction: "in",
        amount: "$3,700",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 302,
    dailyLogStreakDays: 11,
    relatedInsightIds: ["insight-drone-agriculture-growth", "insight-smallholder-financing"],
  },
  {
    id: "prefab-housing-panels",
    name: "Bayanihan Build Panels",
    tagline:
      "Typhoon-rated interlocking wall panels manufactured close to rebuild zones in the Philippines.",
    description:
      "Bayanihan Build makes fiber-cement composite wall panels that interlock like oversized bricks, letting a trained four-person crew erect a typhoon-rated home shell in three days instead of three months. Panels are pressed at small regional plants sited near rebuild zones, cutting freight cost and lead time out of government housing programs. The pilot line is running; the demo house in Tacloban is going up now.",
    category: "Modular Construction",
    stage: "building-mvp",
    coverImageSrc: "/dummy/rnd_project_cover_04.avif",
    founderId: "maricel-santos",
    teamMembers: [
      {
        id: "maricel-santos",
        name: "Maricel Santos",
        avatarImageSrc: "/dummy/profile_image_12.avif",
        role: "Founder & Structural Engineer",
        skills: ["Structural analysis", "Typhoon load codes", "Factory layout"],
        equityShare: "54%",
        effortHoursLogged: 298,
        joinedDate: "Nov 20, 2025",
        isFounder: true,
      },
      {
        id: "josef-tan",
        name: "Josef Tan",
        avatarImageSrc: "/dummy/profile_image_01.avif",
        role: "Manufacturing Lead",
        skills: ["Compression molding", "Lean production", "Quality systems"],
        equityShare: "9.5%",
        effortHoursLogged: 231,
        joinedDate: "Jan 8, 2026",
      },
      {
        id: "anh-nguyen",
        name: "Anh Nguyen",
        avatarImageSrc: "/dummy/profile_image_02.avif",
        role: "Materials Scientist",
        skills: ["Fiber-cement composites", "Accelerated weathering tests"],
        equityShare: "7%",
        effortHoursLogged: 205,
        joinedDate: "Jan 26, 2026",
      },
      {
        id: "rafael-cruz",
        name: "Rafael Cruz",
        avatarImageSrc: "/dummy/profile_image_03.avif",
        role: "Site Operations",
        skills: ["Crew training", "Installation sequencing"],
        equityShare: "4.5%",
        effortHoursLogged: 152,
        joinedDate: "Mar 2, 2026",
      },
      {
        id: "kim-reyes",
        name: "Kim Reyes",
        avatarImageSrc: "/dummy/profile_image_04.avif",
        role: "Finance & Compliance",
        skills: ["Cost accounting", "Government procurement"],
        equityShare: "3.5%",
        effortHoursLogged: 118,
        joinedDate: "Mar 30, 2026",
      },
    ],
    openRoles: [
      {
        id: "prefab-role-industrial-designer",
        projectId: "prefab-housing-panels",
        projectName: "Bayanihan Build Panels",
        roleTitle: "Industrial Designer",
        skills: ["Design for manufacture", "Connection detailing", "3D modeling"],
        equityRange: "1–2.5%",
        commitment: "full-time",
      },
    ],
    milestones: [
      {
        id: "prefab-milestone-panel-formula",
        title: "Lock composite panel formula after weathering tests",
        description:
          "Fiber-cement mix selected after 90-day accelerated weathering and salt-spray exposure.",
        targetDate: "Mar 14, 2026",
        status: "done",
        escrowReleaseAmount: "$5,000",
      },
      {
        id: "prefab-milestone-load-testing",
        title: "Pass simulated 250 km/h wind-load test",
        description:
          "Full wall assembly held design load at the university structures lab with no connection failures.",
        targetDate: "Apr 30, 2026",
        status: "done",
        escrowReleaseAmount: "$7,500",
      },
      {
        id: "prefab-milestone-pilot-line",
        title: "Commission pilot production line",
        description: "First regional press line running at Tacloban with two trained shifts.",
        targetDate: "Jun 12, 2026",
        status: "done",
        escrowReleaseAmount: "$9,000",
      },
      {
        id: "prefab-milestone-demo-house",
        title: "Erect full demo house at Tacloban site",
        description:
          "Complete two-bedroom shell built by a local crew as the public proof point and training site.",
        targetDate: "Jul 30, 2026",
        status: "current",
        escrowReleaseAmount: "$8,000",
      },
      {
        id: "prefab-milestone-certification",
        title: "Obtain national building-code certification",
        description: "Accreditation of the panel system for government-funded housing programs.",
        targetDate: "Sep 18, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$6,500",
      },
      {
        id: "prefab-milestone-first-order",
        title: "Deliver first 50-home government order",
        description: "Panels pressed, delivered, and erected for the first procurement contract.",
        targetDate: "Dec 4, 2026",
        status: "upcoming",
      },
    ],
    dailyLogs: [
      {
        id: "prefab-log-jul-7",
        authorId: "josef-tan",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image02.avif",
        transcriptExcerpt:
          "Press cycle time is down to 22 minutes per panel after we re-sequenced the demolding step — that is 26 panels per shift, up from 19.",
        detail:
          "The demolding fixture change lets the press start the next cycle while the previous panel cures on a side rack. At 26 panels per shift the 50-home order becomes a ten-week production run instead of fourteen. Wrote up the new sequence for the second shift.",
        aiSummaryChips: [
          { kind: "velocity", label: "Panel cycle time down to 22 min" },
          { kind: "progress", label: "26 panels per shift" },
        ],
        isEffortVerified: true,
      },
      {
        id: "prefab-log-jul-6",
        authorId: "maricel-santos",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image03.avif",
        transcriptExcerpt:
          "First wall row of the demo house is set and plumb — the crew hit the interlock tolerances without a single panel rework.",
        detail:
          "This was the moment the whole design gets tested by real hands: a crew of four with two days of training set the base course in under three hours. Roof trusses arrive Thursday. Filming everything for the training curriculum.",
        aiSummaryChips: [{ kind: "progress", label: "Demo house first wall row set" }],
        isEffortVerified: true,
      },
      {
        id: "prefab-log-jul-5",
        authorId: "anh-nguyen",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image04.avif",
        transcriptExcerpt:
          "The humidity chamber's sensor failed mid-run, which voids this week's weathering batch — I sourced a replacement sensor and a borrowed chamber slot at the university.",
        detail:
          "The failed run was a supplementary data set for certification, not on the critical path, but I do not want a gap in the log the auditors will read. University lab can run our coupons Tuesday. Replacement sensor ships from Manila tomorrow.",
        aiSummaryChips: [
          { kind: "blocker", label: "Humidity chamber sensor failed" },
          { kind: "suggestion", label: "Borrow university chamber slot" },
        ],
        isEffortVerified: true,
      },
      {
        id: "prefab-log-jul-4",
        authorId: "rafael-cruz",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image05.avif",
        transcriptExcerpt:
          "Trained the second erection crew today — eight workers from the barangay, all of whom lost homes in the last typhoon season and asked to build the replacements themselves.",
        detail:
          "The training curriculum held up: by afternoon the new crew set practice panels within tolerance unassisted. Their foreman suggested a jig improvement for corner panels that I am passing to Josef. This crew takes the north wall on Monday.",
        aiSummaryChips: [{ kind: "progress", label: "Second erection crew trained" }],
        isEffortVerified: true,
      },
      {
        id: "prefab-log-jul-3",
        authorId: "kim-reyes",
        date: "Jul 3, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image06.avif",
        transcriptExcerpt:
          "Pre-filed the certification paperwork so the review clock starts before the demo house is even finished — the accreditation office confirmed receipt this morning.",
        detail:
          "Certification review takes a statutory 60 days, and nothing stops us filing the documentary sections now and appending the demo-house inspection report later. That could pull the whole go-to-market date forward a month. Also reconciled the June escrow statement.",
        aiSummaryChips: [{ kind: "suggestion", label: "Pre-file certification paperwork" }],
        isEffortVerified: false,
      },
      {
        id: "prefab-log-jul-2",
        authorId: "maricel-santos",
        date: "Jul 2, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image07.avif",
        transcriptExcerpt:
          "Walked the provincial housing board through the pilot line — they left asking for a costed proposal for 200 homes, four times the first order we planned to bid.",
        detail:
          "The board's engineers stress-tested the interlock samples by hand and asked sharp questions about typhoon anchoring, all covered by the load-test data. A 200-home proposal changes our plant-capacity math; Josef and I start the expansion model tomorrow.",
        aiSummaryChips: [
          { kind: "progress", label: "200-home proposal requested" },
          { kind: "velocity", label: "Pipeline 4x larger than planned" },
        ],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "prefab-round-community",
        type: "crowdfunding",
        goalAmount: "$25,000",
        raisedAmount: "$25,000",
        percentageFunded: 100,
        backersCount: 264,
        closesOnDate: "Feb 28, 2026",
        status: "closed",
      },
      {
        id: "prefab-round-seed-equity",
        type: "equity",
        goalAmount: "$120,000",
        raisedAmount: "$78,000",
        percentageFunded: 65,
        backersCount: 19,
        closesOnDate: "Aug 15, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "prefab-escrow-7",
        date: "Jul 1, 2026",
        description: "Angel syndicate tranche 2 — pending fund verification",
        direction: "in",
        amount: "$12,000",
        verificationStatus: "pending",
      },
      {
        id: "prefab-escrow-6",
        date: "Jun 15, 2026",
        description: "Milestone release — pilot production line",
        direction: "out",
        amount: "$9,000",
        linkedMilestoneId: "prefab-milestone-pilot-line",
        verificationStatus: "verified",
      },
      {
        id: "prefab-escrow-5",
        date: "Jun 8, 2026",
        description: "Seed equity deposits — June cohort",
        direction: "in",
        amount: "$26,000",
        verificationStatus: "verified",
      },
      {
        id: "prefab-escrow-4",
        date: "May 20, 2026",
        description: "Seed equity deposits — anchor investor",
        direction: "in",
        amount: "$40,000",
        verificationStatus: "verified",
      },
      {
        id: "prefab-escrow-3",
        date: "May 5, 2026",
        description: "Milestone release — 250 km/h wind-load test",
        direction: "out",
        amount: "$7,500",
        linkedMilestoneId: "prefab-milestone-load-testing",
        verificationStatus: "verified",
      },
      {
        id: "prefab-escrow-2",
        date: "Mar 20, 2026",
        description: "Milestone release — composite panel formula",
        direction: "out",
        amount: "$5,000",
        linkedMilestoneId: "prefab-milestone-panel-formula",
        verificationStatus: "verified",
      },
      {
        id: "prefab-escrow-1",
        date: "Mar 1, 2026",
        description: "Crowdfunding round settlement",
        direction: "in",
        amount: "$25,000",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 587,
    dailyLogStreakDays: 23,
    originProblemReportId: "report-typhoon-housing-backlog-tacloban",
    relatedInsightIds: ["insight-prefab-construction-surge", "insight-solar-hardware-costs"],
  },
  {
    id: "e-waste-recycling-line",
    name: "Sankofa Circuits Recovery",
    tagline:
      "A formalized e-waste recovery line turning Accra's scrap streams into certified copper and gold concentrate.",
    description:
      "Sankofa Circuits replaces open-pit cable burning with a safe, mechanized recovery line: licensed collectors feed sorted e-waste into shredding, separation, and hydrometallurgical recovery stages that out-pay the informal burn yards while eliminating the dioxin exposure around them. The pilot shed already runs at two tonnes a week; the venture round now open funds the full line and a smelter offtake agreement.",
    category: "E-Waste & Recycling",
    stage: "raising-funding",
    coverImageSrc: "/dummy/rnd_project_cover_05.avif",
    founderId: "kwame-mensah",
    teamMembers: [
      {
        id: "kwame-mensah",
        name: "Kwame Mensah",
        avatarImageSrc: "/dummy/profile_image_05.avif",
        role: "Founder & Process Engineer",
        skills: ["Hydrometallurgy", "Plant safety", "Scrap-dealer networks"],
        equityShare: "60%",
        effortHoursLogged: 342,
        joinedDate: "Oct 6, 2025",
        isFounder: true,
      },
      {
        id: "efua-boateng",
        name: "Efua Boateng",
        avatarImageSrc: "/dummy/profile_image_06.avif",
        role: "Operations Manager",
        skills: ["Shift planning", "Safety training", "Procurement"],
        equityShare: "8.5%",
        effortHoursLogged: 276,
        joinedDate: "Dec 1, 2025",
      },
      {
        id: "chidi-nwosu",
        name: "Chidi Nwosu",
        avatarImageSrc: "/dummy/profile_image_07.avif",
        role: "Metallurgical Chemist",
        skills: ["Leaching chemistry", "Assay quality assurance"],
        equityShare: "7%",
        effortHoursLogged: 244,
        joinedDate: "Jan 12, 2026",
      },
      {
        id: "fatima-diallo",
        name: "Fatima Diallo",
        avatarImageSrc: "/dummy/profile_image_08.avif",
        role: "Impact & Compliance Lead",
        skills: ["Basel Convention reporting", "Community health programs"],
        equityShare: "5%",
        effortHoursLogged: 189,
        joinedDate: "Feb 16, 2026",
      },
    ],
    openRoles: [
      {
        id: "ewaste-role-plant-automation-engineer",
        projectId: "e-waste-recycling-line",
        projectName: "Sankofa Circuits Recovery",
        roleTitle: "Plant Automation Engineer",
        skills: ["PLC programming", "Conveyor systems", "Sensor calibration"],
        equityRange: "2–4%",
        commitment: "full-time",
      },
    ],
    milestones: [
      {
        id: "ewaste-milestone-collection-network",
        title: "Sign 25 licensed scrap-collector agreements",
        description:
          "Formal supply agreements paying above informal burn-yard rates for sorted e-waste.",
        targetDate: "Jan 30, 2026",
        status: "done",
        escrowReleaseAmount: "$4,000",
      },
      {
        id: "ewaste-milestone-bench-process",
        title: "Validate bench-scale recovery at 92% copper yield",
        description:
          "Leaching and recovery chemistry proven on representative scrap batches with independent assay confirmation.",
        targetDate: "Mar 22, 2026",
        status: "done",
        escrowReleaseAmount: "$6,000",
      },
      {
        id: "ewaste-milestone-safety-retrofit",
        title: "Complete ventilation and PPE retrofit of pilot shed",
        description:
          "Extraction ventilation, spill containment, and full protective-equipment program for both shifts.",
        targetDate: "May 8, 2026",
        status: "done",
        escrowReleaseAmount: "$5,500",
      },
      {
        id: "ewaste-milestone-pilot-throughput",
        title: "Hit 2 tonnes/week pilot throughput",
        description:
          "Sustained four-week run at target throughput with recovery yields holding above 88%.",
        targetDate: "Jun 25, 2026",
        status: "done",
        escrowReleaseAmount: "$7,000",
      },
      {
        id: "ewaste-milestone-series-round",
        title: "Close $250,000 venture round",
        description: "Round closed and escrow settled to fund the full recovery line build-out.",
        targetDate: "Aug 20, 2026",
        status: "current",
      },
      {
        id: "ewaste-milestone-full-line",
        title: "Commission full recovery line with smelter offtake",
        description:
          "Ten-tonne-per-week line commissioned with a signed concentrate offtake agreement.",
        targetDate: "Nov 30, 2026",
        status: "upcoming",
        escrowReleaseAmount: "$30,000",
      },
    ],
    dailyLogs: [
      {
        id: "ewaste-log-jul-7",
        authorId: "chidi-nwosu",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image08.avif",
        transcriptExcerpt:
          "The independent assay on last month's gold concentrate came back at 99.2% agreement with our in-house numbers — the smelter's quality bar is officially cleared.",
        detail:
          "This was the last technical question in the offtake negotiation. Our in-house assay lab is now credible enough that the smelter will accept our numbers for provisional payment, with quarterly independent verification. Sent the certificates to Kwame for the data room.",
        aiSummaryChips: [
          { kind: "progress", label: "Gold concentrate assay confirmed" },
          { kind: "velocity", label: "Offtake diligence nearly closed" },
        ],
        isEffortVerified: true,
      },
      {
        id: "ewaste-log-jul-6",
        authorId: "kwame-mensah",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image09.avif",
        transcriptExcerpt:
          "Term-sheet redlines came back from the lead investor — the sticking points are down to board composition and the escrow release schedule, both solvable.",
        detail:
          "They accepted the valuation and the milestone-gated escrow structure outright, which tells me the Qatoto ledger history did the convincing. I countered on board seats: two founders, two investors, one independent. Call with counsel tomorrow morning.",
        aiSummaryChips: [{ kind: "progress", label: "Term-sheet redlines returned" }],
        isEffortVerified: true,
      },
      {
        id: "ewaste-log-jul-5",
        authorId: "efua-boateng",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image10.avif",
        transcriptExcerpt:
          "The main conveyor belt splice failed on the morning shift — we lost about four hours of throughput before the crew got the backup splice kit installed.",
        detail:
          "Root cause is belt age, not the splice work; this belt came second-hand with the pilot shed. I priced a new belt and a vulcanized splice service, and I want to add belt replacement to the full-line budget rather than patch again in October.",
        aiSummaryChips: [
          { kind: "blocker", label: "Conveyor splice failure, 4h lost" },
          { kind: "suggestion", label: "Budget belt replacement in full line" },
        ],
        isEffortVerified: true,
      },
      {
        id: "ewaste-log-jul-4",
        authorId: "fatima-diallo",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image11.avif",
        transcriptExcerpt:
          "Proposed publishing our air-quality monitor readings on a public monthly dashboard — the community health committee has asked twice, and we have nothing to hide.",
        detail:
          "Our particulate and dioxin-precursor readings run far below the burn-yard baseline the university measured last year. Publishing monthly makes the contrast undeniable and builds the community case for formalization. Kwame approved; first report goes out August 1.",
        aiSummaryChips: [
          { kind: "suggestion", label: "Publish monthly air-quality data" },
          { kind: "progress", label: "Community health committee engaged" },
        ],
        isEffortVerified: true,
      },
      {
        id: "ewaste-log-jul-3",
        authorId: "kwame-mensah",
        date: "Jul 3, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image12.avif",
        transcriptExcerpt:
          "Data room is 90% complete — uploaded the throughput logs, assay certificates, and the full Qatoto escrow ledger export for investor diligence.",
        detail:
          "The escrow ledger export is doing heavy lifting in diligence: every milestone release is timestamped and verified, so the investors' operational questions are mostly pre-answered. Remaining items are the updated environmental permit and two collector-agreement renewals.",
        aiSummaryChips: [{ kind: "velocity", label: "Diligence data room 90% complete" }],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "ewaste-round-seed-equity",
        type: "equity",
        goalAmount: "$50,000",
        raisedAmount: "$50,000",
        percentageFunded: 100,
        backersCount: 41,
        closesOnDate: "Feb 14, 2026",
        status: "closed",
      },
      {
        id: "ewaste-round-venture",
        type: "venture",
        goalAmount: "$250,000",
        raisedAmount: "$172,500",
        percentageFunded: 69,
        backersCount: 6,
        closesOnDate: "Aug 20, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "ewaste-escrow-8",
        date: "Jul 2, 2026",
        description: "Venture tranche — pending fund verification",
        direction: "in",
        amount: "$32,500",
        verificationStatus: "pending",
      },
      {
        id: "ewaste-escrow-7",
        date: "Jun 27, 2026",
        description: "Milestone release — 2 tonnes/week throughput",
        direction: "out",
        amount: "$7,000",
        linkedMilestoneId: "ewaste-milestone-pilot-throughput",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-6",
        date: "Jun 10, 2026",
        description: "Venture deposits — second institutional check",
        direction: "in",
        amount: "$60,000",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-5",
        date: "May 12, 2026",
        description: "Milestone release — safety retrofit",
        direction: "out",
        amount: "$5,500",
        linkedMilestoneId: "ewaste-milestone-safety-retrofit",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-4",
        date: "May 2, 2026",
        description: "Venture deposits — lead investor first check",
        direction: "in",
        amount: "$80,000",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-3",
        date: "Mar 28, 2026",
        description: "Milestone release — bench-scale recovery validation",
        direction: "out",
        amount: "$6,000",
        linkedMilestoneId: "ewaste-milestone-bench-process",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-2",
        date: "Feb 3, 2026",
        description: "Milestone release — collector network agreements",
        direction: "out",
        amount: "$4,000",
        linkedMilestoneId: "ewaste-milestone-collection-network",
        verificationStatus: "verified",
      },
      {
        id: "ewaste-escrow-1",
        date: "Feb 1, 2026",
        description: "Seed round escrow settlement",
        direction: "in",
        amount: "$50,000",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 468,
    dailyLogStreakDays: 17,
    originProblemReportId: "report-informal-e-waste-burning-accra",
    relatedInsightIds: ["insight-e-waste-volume", "insight-solar-hardware-costs"],
  },
  {
    id: "medical-cold-chain-packaging",
    name: "ThermaSure Med Packaging",
    tagline: "Reusable, sensor-verified cold-chain shippers for specialty pharma across the EU.",
    description:
      "ThermaSure builds reusable pharma shippers that hold 2–8°C for 120 hours using phase-change panels, with embedded telemetry that writes a tamper-proof temperature log for every leg of the journey. Couriers return the shippers into a refurbishment loop, cutting per-shipment packaging cost below single-use gel packs. With three specialty-pharma contracts signed and production at scale, the team is now launching into the Nordic markets.",
    category: "Medical Logistics",
    stage: "go-to-market",
    coverImageSrc: "/dummy/rnd_project_cover_06.avif",
    founderId: "elise-moreau",
    teamMembers: [
      {
        id: "elise-moreau",
        name: "Elise Moreau",
        avatarImageSrc: "/dummy/profile_image_09.avif",
        role: "Founder & CEO",
        skills: ["Pharma logistics", "GDP compliance", "Enterprise sales"],
        equityShare: "51%",
        effortHoursLogged: 412,
        joinedDate: "Jun 10, 2025",
        isFounder: true,
      },
      {
        id: "jonas-weber",
        name: "Jonas Weber",
        avatarImageSrc: "/dummy/profile_image_10.avif",
        role: "Head of Engineering",
        skills: ["Phase-change materials", "IoT telemetry", "ISO 13485"],
        equityShare: "12%",
        effortHoursLogged: 388,
        joinedDate: "Jul 22, 2025",
      },
      {
        id: "ingrid-sorensen",
        name: "Ingrid Sørensen",
        avatarImageSrc: "/dummy/profile_image_11.avif",
        role: "Commercial Director",
        skills: ["Courier partnerships", "Tender bidding", "Pricing"],
        equityShare: "9%",
        effortHoursLogged: 296,
        joinedDate: "Oct 5, 2025",
      },
    ],
    openRoles: [],
    milestones: [
      {
        id: "med-milestone-thermal-validation",
        title: "Pass 120-hour thermal validation at ISTA lab",
        description:
          "Independent lab confirmed 2–8°C hold across summer and winter ambient profiles.",
        targetDate: "Sep 25, 2025",
        status: "done",
        escrowReleaseAmount: "$12,000",
      },
      {
        id: "med-milestone-gdp-audit",
        title: "Clear GDP compliance audit with zero major findings",
        description:
          "Good Distribution Practice audit passed, unlocking regulated pharma shipments.",
        targetDate: "Dec 12, 2025",
        status: "done",
        escrowReleaseAmount: "$15,000",
      },
      {
        id: "med-milestone-courier-integration",
        title: "Integrate telemetry with two EU courier networks",
        description:
          "Live temperature and chain-of-custody data flowing into both couriers' tracking systems.",
        targetDate: "Feb 27, 2026",
        status: "done",
        escrowReleaseAmount: "$18,000",
      },
      {
        id: "med-milestone-production-scale",
        title: "Scale production to 1,000 shippers per month",
        description:
          "Contract manufacturer qualified and refurbishment loop running at target volume.",
        targetDate: "Apr 24, 2026",
        status: "done",
        escrowReleaseAmount: "$25,000",
      },
      {
        id: "med-milestone-first-contracts",
        title: "Sign three specialty-pharma logistics contracts",
        description:
          "Multi-year shipper-fleet agreements with three specialty-pharma distributors.",
        targetDate: "Jun 19, 2026",
        status: "done",
        escrowReleaseAmount: "$20,000",
      },
      {
        id: "med-milestone-market-expansion",
        title: "Launch in Nordic markets",
        description:
          "Distributor agreements and courier coverage live in Denmark, Sweden, and Norway.",
        targetDate: "Sep 10, 2026",
        status: "current",
        escrowReleaseAmount: "$22,000",
      },
    ],
    dailyLogs: [
      {
        id: "med-log-jul-7",
        authorId: "ingrid-sorensen",
        date: "Jul 7, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image01.avif",
        transcriptExcerpt:
          "Nordic distributor shortlist is final — two candidates in Copenhagen, one in Stockholm, all with existing GDP-certified warehousing.",
        detail:
          "All three cleared our compliance screen and two already handle competing single-use shippers, so the reusable pitch lands on educated ears. Commercial terms drafts go out tomorrow; I want signatures before the August holiday freeze hits Scandinavia.",
        aiSummaryChips: [
          { kind: "progress", label: "Nordic distributor shortlist final" },
          { kind: "velocity", label: "Ahead of Q3 expansion plan" },
        ],
        isEffortVerified: true,
      },
      {
        id: "med-log-jul-6",
        authorId: "jonas-weber",
        date: "Jul 6, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image02.avif",
        transcriptExcerpt:
          "The firmware over-the-air signing certificate expires in August and the renewal is stuck in the certificate authority's verification queue — I escalated and prepared a fallback plan.",
        detail:
          "Without the renewal, fleet firmware updates pause; shippers keep working but we cannot push the new battery-saver release. Fallback is a staged manual update at the refurbishment depots, which covers 80% of the fleet within a month anyway. Escalation ticket is with the CA's enterprise desk.",
        aiSummaryChips: [
          { kind: "blocker", label: "OTA signing cert renewal delayed" },
          { kind: "suggestion", label: "Stage manual updates at depots" },
        ],
        isEffortVerified: true,
      },
      {
        id: "med-log-jul-5",
        authorId: "elise-moreau",
        date: "Jul 5, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image03.avif",
        transcriptExcerpt:
          "Contract number three is countersigned — the Lyon distributor committed to a 400-shipper fleet with a three-year term and quarterly volume ramps.",
        detail:
          "This is the contract that started as a cold outreach after their couriers kept failing temperature audits. Their audit-failure problem became our reference case. The signed fleet commitment also releases the final contract milestone in escrow.",
        aiSummaryChips: [{ kind: "progress", label: "Third pharma contract countersigned" }],
        isEffortVerified: true,
      },
      {
        id: "med-log-jul-4",
        authorId: "jonas-weber",
        date: "Jul 4, 2026",
        videoThumbnailSrc: "/dummy/thumbnail_image04.avif",
        transcriptExcerpt:
          "Return-logistics cycle time is down to six days average — refurbished shippers are back in courier depots almost twice as fast as in March.",
        detail:
          "The gain came from pre-positioning phase-change panels at the two busiest depots so refurbishment no longer waits on panel recharging. At six days, fleet utilization supports the Nordic launch without buying extra shippers this quarter.",
        aiSummaryChips: [{ kind: "velocity", label: "Refurbishment cycle down to 6 days" }],
        isEffortVerified: true,
      },
    ],
    fundingRounds: [
      {
        id: "med-round-series-a",
        type: "venture",
        goalAmount: "$400,000",
        raisedAmount: "$400,000",
        percentageFunded: 100,
        backersCount: 4,
        closesOnDate: "Nov 30, 2025",
        status: "closed",
      },
      {
        id: "med-round-growth",
        type: "venture",
        goalAmount: "$600,000",
        raisedAmount: "$540,000",
        percentageFunded: 90,
        backersCount: 7,
        closesOnDate: "Jul 31, 2026",
        status: "open",
      },
    ],
    escrowLedger: [
      {
        id: "med-escrow-7",
        date: "Jul 3, 2026",
        description: "Growth round tranche — pending fund verification",
        direction: "in",
        amount: "$90,000",
        verificationStatus: "pending",
      },
      {
        id: "med-escrow-6",
        date: "Jun 24, 2026",
        description: "Milestone release — three pharma contracts signed",
        direction: "out",
        amount: "$20,000",
        linkedMilestoneId: "med-milestone-first-contracts",
        verificationStatus: "verified",
      },
      {
        id: "med-escrow-5",
        date: "Jun 2, 2026",
        description: "Growth round deposits — second close",
        direction: "in",
        amount: "$250,000",
        verificationStatus: "verified",
      },
      {
        id: "med-escrow-4",
        date: "Apr 30, 2026",
        description: "Milestone release — production at 1,000 shippers/month",
        direction: "out",
        amount: "$25,000",
        linkedMilestoneId: "med-milestone-production-scale",
        verificationStatus: "verified",
      },
      {
        id: "med-escrow-3",
        date: "Apr 12, 2026",
        description: "Growth round deposits — first close",
        direction: "in",
        amount: "$200,000",
        verificationStatus: "verified",
      },
      {
        id: "med-escrow-2",
        date: "Mar 4, 2026",
        description: "Milestone release — courier telemetry integration",
        direction: "out",
        amount: "$18,000",
        linkedMilestoneId: "med-milestone-courier-integration",
        verificationStatus: "verified",
      },
      {
        id: "med-escrow-1",
        date: "Dec 5, 2025",
        description: "Series A escrow settlement",
        direction: "in",
        amount: "$400,000",
        verificationStatus: "verified",
      },
    ],
    watchersCount: 921,
    dailyLogStreakDays: 34,
    relatedInsightIds: ["insight-pharma-logistics-compliance", "insight-cold-storage-demand"],
  },
];

export const MOCK_TRENDING_SIGNALS: TrendingSignal[] = [
  {
    id: "signal-cold-chain-east-africa",
    rank: 1,
    category: "Cold Chain & Refrigeration",
    region: "East Africa",
    demandScore: 92,
    trendDirection: "up",
    relatedProjectsCount: 3,
  },
  {
    id: "signal-water-sanitation-south-asia",
    rank: 2,
    category: "Water & Sanitation",
    region: "South Asia",
    demandScore: 88,
    trendDirection: "up",
    relatedProjectsCount: 2,
  },
  {
    id: "signal-modular-construction-southeast-asia",
    rank: 3,
    category: "Modular Construction",
    region: "Southeast Asia",
    demandScore: 84,
    trendDirection: "up",
    relatedProjectsCount: 2,
  },
  {
    id: "signal-e-waste-west-africa",
    rank: 4,
    category: "E-Waste & Recycling",
    region: "West Africa",
    demandScore: 79,
    trendDirection: "up",
    relatedProjectsCount: 1,
  },
  {
    id: "signal-precision-agriculture-latin-america",
    rank: 5,
    category: "Precision Agriculture",
    region: "Latin America",
    demandScore: 74,
    trendDirection: "up",
    relatedProjectsCount: 2,
  },
  {
    id: "signal-medical-logistics-europe",
    rank: 6,
    category: "Medical Logistics",
    region: "Europe",
    demandScore: 71,
    trendDirection: "flat",
    relatedProjectsCount: 1,
  },
  {
    id: "signal-off-grid-solar-sub-saharan-africa",
    rank: 7,
    category: "Off-Grid Solar",
    region: "Sub-Saharan Africa",
    demandScore: 64,
    trendDirection: "flat",
    relatedProjectsCount: 2,
  },
  {
    id: "signal-smallholder-finance-east-africa",
    rank: 8,
    category: "Smallholder Finance",
    region: "East Africa",
    demandScore: 58,
    trendDirection: "down",
    relatedProjectsCount: 0,
  },
];

// Flattened from the projects so role cards and project pages never drift apart.
export const MOCK_OPEN_ROLES: OpenRole[] = MOCK_RESEARCH_PROJECTS.flatMap(
  (project) => project.openRoles,
);

// People browsing-marketplace fixtures for /research-and-development/talent.
// Skills line up with the project categories above so the talent filter chips
// always have hits.
export const MOCK_TALENT_PROFILES: TalentProfile[] = [
  {
    id: "talent-amara-okafor",
    name: "Amara Okafor",
    avatarImageSrc: "/dummy/profile_image_01.avif",
    headlineRole: "Embedded Systems Engineer",
    skills: ["Firmware", "Sensor Networks", "Power Electronics"],
    equityAsk: "2–4%",
    commitment: "full-time",
    locationLabel: "Lagos, Nigeria",
    availability: "open-to-work",
    projectsCompletedCount: 4,
    effortHoursLogged: 1180,
  },
  {
    id: "talent-priya-krishnan",
    name: "Priya Krishnan",
    avatarImageSrc: "/dummy/profile_image_02.avif",
    headlineRole: "Water Treatment Chemist",
    skills: ["Membrane Filtration", "Water & Sanitation", "Lab Validation"],
    equityAsk: "3–5%",
    commitment: "full-time",
    locationLabel: "Chennai, India",
    availability: "open-to-work",
    projectsCompletedCount: 3,
    effortHoursLogged: 940,
  },
  {
    id: "talent-tomas-alvarez",
    name: "Tomás Álvarez",
    avatarImageSrc: "/dummy/profile_image_03.avif",
    headlineRole: "Drone Flight-Systems Developer",
    skills: ["Precision Agriculture", "Flight Control", "Computer Vision"],
    equityAsk: "1.5–3%",
    commitment: "part-time",
    locationLabel: "Cusco, Peru",
    availability: "open-to-offers",
    projectsCompletedCount: 5,
    effortHoursLogged: 1420,
  },
  {
    id: "talent-mei-lin-chua",
    name: "Mei Lin Chua",
    avatarImageSrc: "/dummy/profile_image_04.avif",
    headlineRole: "Industrial Designer",
    skills: ["Modular Construction", "CAD", "Design for Manufacture"],
    equityAsk: "2–3%",
    commitment: "full-time",
    locationLabel: "Tacloban, Philippines",
    availability: "open-to-work",
    projectsCompletedCount: 2,
    effortHoursLogged: 760,
  },
  {
    id: "talent-yaw-asante",
    name: "Yaw Asante",
    avatarImageSrc: "/dummy/profile_image_05.avif",
    headlineRole: "Materials Recovery Specialist",
    skills: ["E-Waste & Recycling", "Process Safety", "Plant Operations"],
    equityAsk: "2–4%",
    commitment: "full-time",
    locationLabel: "Accra, Ghana",
    availability: "open-to-offers",
    projectsCompletedCount: 3,
    effortHoursLogged: 1050,
  },
  {
    id: "talent-claire-dubois",
    name: "Claire Dubois",
    avatarImageSrc: "/dummy/profile_image_06.avif",
    headlineRole: "Cold-Chain Compliance Lead",
    skills: ["Medical Logistics", "Cold Chain", "Regulatory Affairs"],
    equityAsk: "1–2%",
    commitment: "part-time",
    locationLabel: "Lyon, France",
    availability: "open-to-work",
    projectsCompletedCount: 6,
    effortHoursLogged: 1870,
  },
  {
    id: "talent-rashida-begum",
    name: "Rashida Begum",
    avatarImageSrc: "/dummy/profile_image_11.avif",
    headlineRole: "Field Research Coordinator",
    skills: ["Market Research", "Water & Sanitation", "Community Surveys"],
    equityAsk: "1–2.5%",
    commitment: "part-time",
    locationLabel: "Khulna, Bangladesh",
    availability: "open-to-work",
    projectsCompletedCount: 2,
    effortHoursLogged: 620,
  },
  {
    id: "talent-viktor-lindqvist",
    name: "Viktor Lindqvist",
    avatarImageSrc: "/dummy/profile_image_12.avif",
    headlineRole: "Supply-Chain Analyst",
    skills: ["Medical Logistics", "Procurement", "Cost Modeling"],
    equityAsk: "1.5–3%",
    commitment: "hobby",
    locationLabel: "Gothenburg, Sweden",
    availability: "open-to-offers",
    projectsCompletedCount: 1,
    effortHoursLogged: 310,
  },
  {
    id: "talent-nia-mwangi",
    name: "Nia Mwangi",
    avatarImageSrc: "/dummy/profile_photo_girl.avif",
    headlineRole: "Solar Hardware Engineer",
    skills: ["Cold Chain", "Off-Grid Solar", "Thermal Systems"],
    equityAsk: "3–5%",
    commitment: "hobby",
    locationLabel: "Nakuru, Kenya",
    availability: "unavailable",
    projectsCompletedCount: 4,
    effortHoursLogged: 1330,
  },
];

// Confidence signal per project for the /funding deal-flow view (0–100, drives
// the meter width). Display-only mock — the backend derives the real score from
// log streaks and verified milestones later. solar-cold-storage matches the
// hardcoded meter on the project Funding tab.
export const MOCK_INVESTOR_CONFIDENCE_BY_PROJECT_ID: Record<string, number> = {
  "solar-cold-storage": 78,
  "modular-water-purification": 64,
  "agricultural-drone-kits": 71,
  "prefab-housing-panels": 83,
  "e-waste-recycling-line": 76,
  "medical-cold-chain-packaging": 91,
};
