// Mock store data extracted from `store.ts`. These in-file MOCK_* constants are
// the fallback the getters in `store.ts` return when `QATOTO_STORE_API_URL` is
// unset or the upstream call fails. Display data only — the Express backend is
// the source of truth and must re-derive anything trusted.

import type {
  B2BLink,
  HeroSlide,
  Pathway,
  ProductRail,
  StoreCategory,
  StoreHome,
  StoreProduct,
} from "@/types/store";

// Dummy hover tints, cycled by index. The backend will eventually send a real
// `hoverBg` per card; until then we fan these out so cards light up like Home.
const HOVER_PALETTE = [
  "group-hover:bg-yellow-100",
  "group-hover:bg-amber-100",
  "group-hover:bg-green-100",
  "group-hover:bg-blue-100",
  "group-hover:bg-red-100",
];
export const hoverAt = (i: number) => HOVER_PALETTE[i % HOVER_PALETTE.length];

const HERO_SLIDES: HeroSlide[] = [
  {
    id: "1",
    imageSrc: "/dummy/store_hero.avif",
    title: "PrecisionFlame",
    subtitle: "Timer 2 burner gas stove",
    href: "/store/pathway/steel-roll",
  },
  {
    id: "2",
    imageSrc: "/dummy/pathways_3.avif",
    title: "Bomber Drone Classic",
    subtitle: "Affordable drone for war",
    href: "/store/pathway/bomber-drone-classic",
  },
  {
    id: "3",
    imageSrc: "/dummy/pathways_4.avif",
    title: "Tata Cold Steel Roll",
    subtitle: "Industrial grade cold-rolled steel",
    href: "/store/pathway/steel-roll",
  },
];

const ROOT_CATEGORY_SLUGS = [
  "clothes",
  "furniture",
  "accessories",
  "beauty",
  "shoes",
  "bags",
  "machinery",
  "jewelry",
];

// Flat slug -> node map. Catch-all route looks up the last segment here, so
// every slug is globally unique. Empty `childrenSlugs` marks a leaf.
export const MOCK_CATEGORIES: Record<string, StoreCategory> = {
  clothes: {
    slug: "clothes",
    name: "Clothes",
    imageSrc: "/dummy/clothes.avif",
    childrenSlugs: [],
  },
  accessories: {
    slug: "accessories",
    name: "Accessories",
    imageSrc: "/dummy/accessories.avif",
    childrenSlugs: [],
  },
  beauty: {
    slug: "beauty",
    name: "Beauty",
    imageSrc: "/dummy/beauty.avif",
    childrenSlugs: [],
  },
  furniture: {
    slug: "furniture",
    name: "Furniture",
    imageSrc: "/dummy/furniture.avif",
    childrenSlugs: [
      "outdoor-furniture",
      "home-furniture",
      "commercial-furniture",
      "kids-furniture",
      "furniture-hardware",
      "furniture-parts",
      "furniture-accessories",
      "other-furniture",
    ],
  },
  shoes: {
    slug: "shoes",
    name: "Shoes",
    imageSrc: "/dummy/shoes.avif",
    childrenSlugs: [],
  },
  bags: {
    slug: "bags",
    name: "Bags",
    imageSrc: "/dummy/bags.avif",
    childrenSlugs: [],
  },
  machinery: {
    slug: "machinery",
    name: "Machinery",
    imageSrc: "/dummy/machinery.avif",
    childrenSlugs: [],
  },
  jewelry: {
    slug: "jewelry",
    name: "Jewelry",
    imageSrc: "/dummy/jewelry.avif",
    childrenSlugs: [],
  },
  "outdoor-furniture": {
    slug: "outdoor-furniture",
    name: "Outdoor Furniture",
    imageSrc: "/dummy/outdoor_furniture.avif",
    childrenSlugs: [],
  },
  "home-furniture": {
    slug: "home-furniture",
    name: "Home Furniture",
    imageSrc: "/dummy/home_furniture.avif",
    childrenSlugs: [
      "sofas",
      "beds",
      "chairs",
      "coat-racks",
      "stools-and-ottomans",
      "tables",
      "vanity",
      "cabinets",
    ],
  },
  "commercial-furniture": {
    slug: "commercial-furniture",
    name: "Commercial Furniture",
    imageSrc: "/dummy/commercial_furniture.avif",
    childrenSlugs: [],
  },
  "kids-furniture": {
    slug: "kids-furniture",
    name: "Kid's Furniture",
    imageSrc: "/dummy/kid's_furniture.avif",
    childrenSlugs: [],
  },
  "furniture-hardware": {
    slug: "furniture-hardware",
    name: "Furniture Hardware",
    imageSrc: "/dummy/furniture_hardware.avif",
    childrenSlugs: [],
  },
  "furniture-parts": {
    slug: "furniture-parts",
    name: "Furniture Parts",
    imageSrc: "/dummy/furniture_parts.avif",
    childrenSlugs: [],
  },
  "furniture-accessories": {
    slug: "furniture-accessories",
    name: "Furniture Accessories",
    imageSrc: "/dummy/furniture_accessories.avif",
    childrenSlugs: [],
  },
  "other-furniture": {
    slug: "other-furniture",
    name: "Other Furniture",
    imageSrc: "/dummy/other_furniture.avif",
    childrenSlugs: [],
  },
  sofas: {
    slug: "sofas",
    name: "Sofas",
    imageSrc: "/dummy/sofas.avif",
    childrenSlugs: [],
  },
  beds: {
    slug: "beds",
    name: "Beds",
    imageSrc: "/dummy/beds.avif",
    childrenSlugs: [],
  },
  chairs: {
    slug: "chairs",
    name: "Chairs",
    imageSrc: "/dummy/chairs.avif",
    childrenSlugs: [
      "living-room-chair",
      "gaming-chair",
      "dining-chair",
      "office-chair",
      "chaise-lounge",
      "recliner",
      "stacking-chair",
      "massage-chair",
    ],
  },
  "coat-racks": {
    slug: "coat-racks",
    name: "Coat Racks",
    imageSrc: "/dummy/coat_racks.avif",
    childrenSlugs: [],
  },
  "stools-and-ottomans": {
    slug: "stools-and-ottomans",
    name: "Stools and Ottomans",
    imageSrc: "/dummy/stools_and_ottomans.avif",
    childrenSlugs: [],
  },
  tables: {
    slug: "tables",
    name: "Tables",
    imageSrc: "/dummy/tables.avif",
    childrenSlugs: [],
  },
  vanity: {
    slug: "vanity",
    name: "Vanity",
    imageSrc: "/dummy/vanity.avif",
    childrenSlugs: [],
  },
  cabinets: {
    slug: "cabinets",
    name: "Cabinets",
    imageSrc: "/dummy/cabinets.avif",
    childrenSlugs: [],
  },
  "living-room-chair": {
    slug: "living-room-chair",
    name: "Living Room Chair",
    imageSrc: "/dummy/living_room_chair.avif",
    childrenSlugs: [],
  },
  "gaming-chair": {
    slug: "gaming-chair",
    name: "Gaming Chair",
    imageSrc: "/dummy/gaming_chair.avif",
    childrenSlugs: [],
  },
  "dining-chair": {
    slug: "dining-chair",
    name: "Dining Chair",
    imageSrc: "/dummy/dining_chair.avif",
    childrenSlugs: [],
  },
  "office-chair": {
    slug: "office-chair",
    name: "Office Chair",
    imageSrc: "/dummy/office_chair.avif",
    childrenSlugs: [],
  },
  "chaise-lounge": {
    slug: "chaise-lounge",
    name: "Chaise Lounge",
    imageSrc: "/dummy/chaise_lounge.avif",
    childrenSlugs: [],
  },
  recliner: {
    slug: "recliner",
    name: "Recliner",
    imageSrc: "/dummy/recliner.avif",
    childrenSlugs: [],
  },
  "stacking-chair": {
    slug: "stacking-chair",
    name: "Stacking Chair",
    imageSrc: "/dummy/stacking_chair.avif",
    childrenSlugs: [],
  },
  "massage-chair": {
    slug: "massage-chair",
    name: "Massage Chair",
    imageSrc: "/dummy/massage_chair.avif",
    childrenSlugs: [],
  },
};

// Each product feed has its OWN mock array below — no shared source, no
// client-side reshuffle. The backend serves each feed as an independent list
// (the `rails` array in `/store/home`); these mocks mirror that 1:1 so swapping
// in the real API means dropping one array per feed, nothing else.
function railOf(id: string, title: string, products: StoreProduct[]): ProductRail {
  return {
    id,
    title,
    href: `/store/feed/${id}`,
    products: products.map((p, i) => ({ ...p, hoverBg: hoverAt(i) })),
  };
}

// --- What's New: freshly listed products ---
const WHATS_NEW_PRODUCTS: StoreProduct[] = [
  {
    id: "smart-thermostat",
    name: "Smart Thermostat",
    subtitle: "Wi-Fi climate controller",
    imageSrc: "/dummy/pathways_1.avif",
    price: "$149",
    href: "/store/pathway/smart-thermostat",
  },
  {
    id: "ev-charger",
    name: "Home EV Charger",
    subtitle: "11kW wall-mounted unit",
    imageSrc: "/dummy/pathways_2.avif",
    price: "$640",
    href: "/store/pathway/ev-charger",
  },
  {
    id: "solar-panel-kit",
    name: "Solar Panel Kit",
    subtitle: "400W monocrystalline",
    imageSrc: "/dummy/pathways_3.avif",
    price: "$320",
    href: "/store/pathway/solar-panel-kit",
  },
  {
    id: "robot-vacuum",
    name: "Robot Vacuum",
    subtitle: "LiDAR mapping, self-empty",
    imageSrc: "/dummy/pathways_4.avif",
    price: "$499",
    href: "/store/pathway/robot-vacuum",
  },
  {
    id: "air-purifier",
    name: "HEPA Air Purifier",
    subtitle: "Covers 800 sq ft",
    imageSrc: "/dummy/pathways_5.avif",
    price: "$210",
    href: "/store/pathway/air-purifier",
  },
];

// --- Popular: best-moving catalogue staples ---
const POPULAR_PRODUCTS: StoreProduct[] = [
  {
    id: "steel-roll",
    name: "Steel Roll",
    subtitle: "Tata Cold Steel Roll",
    imageSrc: "/dummy/thumbnail_image01.avif",
    price: "$890 / ton",
    href: "/store/pathway/steel-roll",
  },
  {
    id: "industrial-bearing",
    name: "Industrial Bearing Set",
    subtitle: "Sealed ball bearings, pack of 50",
    imageSrc: "/dummy/thumbnail_image02.avif",
    price: "$75",
    href: "/store/pathway/industrial-bearing",
  },
  {
    id: "copper-wire-spool",
    name: "Copper Wire Spool",
    subtitle: "99.9% pure, 100m",
    imageSrc: "/dummy/thumbnail_image03.avif",
    price: "$140 / spool",
    href: "/store/pathway/copper-wire-spool",
  },
  {
    id: "hydraulic-pump",
    name: "Hydraulic Pump",
    subtitle: "3000 PSI gear pump",
    imageSrc: "/dummy/thumbnail_image04.avif",
    price: "$430",
    href: "/store/pathway/hydraulic-pump",
  },
  {
    id: "pvc-pipe-bundle",
    name: "PVC Pipe Bundle",
    subtitle: "Schedule 40, 20-pack",
    imageSrc: "/dummy/thumbnail_image05.avif",
    price: "$60 / bundle",
    href: "/store/pathway/pvc-pipe-bundle",
  },
];

// --- For You: personalised recommendations ---
const FOR_YOU_PRODUCTS: StoreProduct[] = [
  {
    id: "louis-vuitton-collection",
    name: "Louis Vuitton Collection",
    subtitle: "Full seasonal look",
    imageSrc: "/dummy/thumbnail_image06.avif",
    price: "$4,250",
    href: "/store/pathway/louis-vuitton-collection",
  },
  {
    id: "p-designs",
    name: "P Designs",
    subtitle: "UI/UX design studio kit",
    imageSrc: "/dummy/thumbnail_image07.avif",
    price: "$1,200",
    href: "/store/pathway/p-designs",
  },
  {
    id: "leather-briefcase",
    name: "Leather Briefcase",
    subtitle: "Full-grain, handmade",
    imageSrc: "/dummy/thumbnail_image08.avif",
    price: "$680",
    href: "/store/pathway/leather-briefcase",
  },
  {
    id: "mechanical-keyboard",
    name: "Mechanical Keyboard",
    subtitle: "Hot-swap, 75% layout",
    imageSrc: "/dummy/thumbnail_image09.avif",
    price: "$160",
    href: "/store/pathway/mechanical-keyboard",
  },
  {
    id: "ergonomic-chair",
    name: "Ergonomic Office Chair",
    subtitle: "Mesh back, lumbar support",
    imageSrc: "/dummy/thumbnail_image10.avif",
    price: "$540",
    href: "/store/pathway/ergonomic-chair",
  },
];

// --- Trending: spiking demand right now ---
const TRENDING_PRODUCTS: StoreProduct[] = [
  {
    id: "bomber-drone-classic",
    name: "Bomber Drone Classic",
    subtitle: "Affordable drone for war",
    imageSrc: "/dummy/thumbnail_image11.avif",
    price: "$12,400",
    href: "/store/pathway/bomber-drone-classic",
  },
  {
    id: "thermal-scope",
    name: "Thermal Scope",
    subtitle: "640x480 sensor, 1000m range",
    imageSrc: "/dummy/thumbnail_image12.avif",
    price: "$3,900",
    href: "/store/pathway/thermal-scope",
  },
  {
    id: "steel-nail",
    name: "Steel Nail",
    subtitle: "Carbon steel concrete masonry nail",
    imageSrc: "/dummy/pathways_3.avif",
    price: "$3 / box",
    href: "/store/pathway/steel-nail",
  },
  {
    id: "tactical-backpack",
    name: "Tactical Backpack",
    subtitle: "45L MOLLE, water-resistant",
    imageSrc: "/dummy/pathways_4.avif",
    price: "$120",
    href: "/store/pathway/tactical-backpack",
  },
  {
    id: "field-generator",
    name: "Field Generator",
    subtitle: "2000W portable inverter",
    imageSrc: "/dummy/pathways_5.avif",
    price: "$1,150",
    href: "/store/pathway/field-generator",
  },
];

const MOCK_RAILS: ProductRail[] = [
  railOf("whats-new", "What's New", WHATS_NEW_PRODUCTS),
  railOf("popular", "Popular", POPULAR_PRODUCTS),
  railOf("for-you", "For You", FOR_YOU_PRODUCTS),
  railOf("trending", "Trending", TRENDING_PRODUCTS),
];

// --- Leaf-category feeds: each its own array too ---
const BEST_SELLERS_PRODUCTS: StoreProduct[] = [
  {
    id: "lv-folding-chair",
    name: "Louis Vuitton Folding Metal Living Room Chair(Finish Color - Red, Pre-assembled)",
    subtitle: "Pre-assembled, Red",
    imageSrc: "/dummy/chair_raspberry_red.avif",
    price: "$753.80",
    href: "/store/product/lv-folding-chair",
  },
  {
    id: "tool-chest",
    name: "Rolling Tool Chest",
    subtitle: "7-drawer steel cabinet",
    imageSrc: "/dummy/thumbnail_image02.avif",
    price: "$380",
    href: "/store/pathway/tool-chest",
  },
  {
    id: "work-gloves",
    name: "Cut-resistant Work Gloves",
    subtitle: "Level 5, 12-pack",
    imageSrc: "/dummy/thumbnail_image03.avif",
    price: "$45 / pack",
    href: "/store/pathway/work-gloves",
  },
  {
    id: "led-floodlight",
    name: "LED Floodlight",
    subtitle: "150W, IP66 outdoor",
    imageSrc: "/dummy/thumbnail_image04.avif",
    price: "$70",
    href: "/store/pathway/led-floodlight",
  },
];

const NEW_ARRIVALS_PRODUCTS: StoreProduct[] = [
  {
    id: "smart-lock",
    name: "Smart Door Lock",
    subtitle: "Fingerprint + app unlock",
    imageSrc: "/dummy/thumbnail_image05.avif",
    price: "$190",
    href: "/store/pathway/smart-lock",
  },
  {
    id: "standing-desk",
    name: "Standing Desk",
    subtitle: "Electric, dual motor",
    imageSrc: "/dummy/thumbnail_image06.avif",
    price: "$420",
    href: "/store/pathway/standing-desk",
  },
  {
    id: "wireless-earbuds",
    name: "Wireless Earbuds",
    subtitle: "ANC, 30h battery",
    imageSrc: "/dummy/thumbnail_image07.avif",
    price: "$95",
    href: "/store/pathway/wireless-earbuds",
  },
  {
    id: "desk-lamp",
    name: "LED Desk Lamp",
    subtitle: "Dimmable, USB-C charging",
    imageSrc: "/dummy/thumbnail_image08.avif",
    price: "$48",
    href: "/store/pathway/desk-lamp",
  },
];

const TOP_RATED_PRODUCTS: StoreProduct[] = [
  {
    id: "espresso-machine",
    name: "Espresso Machine",
    subtitle: "15-bar, dual boiler",
    imageSrc: "/dummy/thumbnail_image09.avif",
    price: "$560",
    href: "/store/pathway/espresso-machine",
  },
  {
    id: "chef-knife-set",
    name: "Chef Knife Set",
    subtitle: "Damascus steel, 8-piece",
    imageSrc: "/dummy/thumbnail_image10.avif",
    price: "$220",
    href: "/store/pathway/chef-knife-set",
  },
  {
    id: "cast-iron-skillet",
    name: "Cast Iron Skillet",
    subtitle: "Pre-seasoned, 12 inch",
    imageSrc: "/dummy/thumbnail_image11.avif",
    price: "$40",
    href: "/store/pathway/cast-iron-skillet",
  },
  {
    id: "stand-mixer",
    name: "Stand Mixer",
    subtitle: "5.5L, 10-speed",
    imageSrc: "/dummy/thumbnail_image12.avif",
    price: "$310",
    href: "/store/pathway/stand-mixer",
  },
];

export const MOCK_LEAF_RAILS: ProductRail[] = [
  railOf("best-sellers", "Best Sellers", BEST_SELLERS_PRODUCTS),
  railOf("new-arrivals", "New Arrivals", NEW_ARRIVALS_PRODUCTS),
  railOf("top-rated", "Top Rated", TOP_RATED_PRODUCTS),
];

// --- Per-category product feeds ---
// Earlier every category page reused the same `MOCK_LEAF_RAILS`, so Chairs,
// Sofas, Beauty, Machinery, … all showed identical "Best Sellers / New
// Arrivals" products. Now each slug owns a themed pool below, and the rails are
// titled with the category name so the hierarchy context is visible (e.g.
// "Popular in Gaming Chair"). Drilling parent -> child changes the feed because
// each node has its own pool. The backend will serve these per-category; the
// mocks mirror that 1:1.
function prod(
  id: string,
  name: string,
  subtitle: string,
  imageSrc: string,
  price: string,
): StoreProduct {
  return { id, name, subtitle, imageSrc, price, href: `/store/product/${id}` };
}

// Build three category-scoped rails from a themed pool. A sliding window of 4
// over the 6-item pool gives each rail a distinct lead set while keeping the
// realistic overlap a real store has (a product can be both popular and
// top-rated). React keys are `${rail.id}-${product.id}`, so the overlap is safe.
function railsForCategory(slug: string, name: string, pool: StoreProduct[]): ProductRail[] {
  const win = (start: number) =>
    Array.from({ length: Math.min(4, pool.length) }, (_, k) => pool[(start + k) % pool.length]);
  return [
    railOf(`${slug}-new`, `New in ${name}`, win(0)),
    railOf(`${slug}-popular`, `Popular in ${name}`, win(2)),
    railOf(`${slug}-top`, `Top Rated ${name}`, win(4)),
  ];
}

const CATEGORY_PRODUCT_POOLS: Record<string, StoreProduct[]> = {
  // --- Root categories ---
  clothes: [
    prod(
      "denim-jacket",
      "Denim Jacket",
      "Washed indigo, unisex",
      "/dummy/thumbnail_image01.avif",
      "$89",
    ),
    prod(
      "linen-shirt",
      "Linen Shirt",
      "Breathable summer fit",
      "/dummy/thumbnail_image02.avif",
      "$54",
    ),
    prod(
      "wool-overcoat",
      "Wool Overcoat",
      "Italian wool blend",
      "/dummy/thumbnail_image03.avif",
      "$240",
    ),
    prod(
      "cotton-tee",
      "Cotton Tee 3-pack",
      "Heavyweight crew neck",
      "/dummy/thumbnail_image04.avif",
      "$39",
    ),
    prod("slim-chinos", "Slim Chinos", "Stretch twill", "/dummy/thumbnail_image05.avif", "$62"),
    prod(
      "fleece-hoodie",
      "Fleece Hoodie",
      "Brushed interior",
      "/dummy/thumbnail_image06.avif",
      "$58",
    ),
  ],
  accessories: [
    prod(
      "leather-belt",
      "Leather Belt",
      "Full-grain, brass buckle",
      "/dummy/thumbnail_image07.avif",
      "$45",
    ),
    prod("silk-scarf", "Silk Scarf", "Hand-rolled edges", "/dummy/thumbnail_image08.avif", "$70"),
    prod(
      "polarized-sunglasses",
      "Polarized Sunglasses",
      "UV400 acetate",
      "/dummy/thumbnail_image09.avif",
      "$120",
    ),
    prod("bifold-wallet", "Bifold Wallet", "RFID blocking", "/dummy/thumbnail_image10.avif", "$55"),
    prod("ribbed-beanie", "Ribbed Beanie", "Merino wool", "/dummy/thumbnail_image11.avif", "$28"),
    prod(
      "steel-cufflinks",
      "Steel Cufflinks",
      "Brushed finish",
      "/dummy/thumbnail_image12.avif",
      "$40",
    ),
  ],
  beauty: [
    prod(
      "vitamin-c-serum",
      "Vitamin C Serum",
      "Brightening, 30ml",
      "/dummy/recommended_for_you_01.avif",
      "$32",
    ),
    prod(
      "matte-lipstick",
      "Matte Lipstick",
      "Long-wear, 12 shades",
      "/dummy/recommended_for_you_02.avif",
      "$24",
    ),
    prod(
      "jade-roller",
      "Jade Face Roller",
      "Cooling massage",
      "/dummy/recommended_for_you_03.avif",
      "$18",
    ),
    prod(
      "sheet-mask",
      "Hydrating Sheet Mask",
      "Pack of 10",
      "/dummy/recommended_for_you_04.avif",
      "$22",
    ),
    prod(
      "eau-de-parfum",
      "Eau de Parfum",
      "Amber & oud, 50ml",
      "/dummy/recommended_for_you_05.avif",
      "$95",
    ),
    prod(
      "liquid-foundation",
      "Liquid Foundation",
      "Buildable, 40 shades",
      "/dummy/recommended_for_you_06.avif",
      "$38",
    ),
  ],
  shoes: [
    prod(
      "running-sneakers",
      "Running Sneakers",
      "Carbon-plate midsole",
      "/dummy/trending01.avif",
      "$140",
    ),
    prod("leather-loafers", "Leather Loafers", "Hand-stitched", "/dummy/trending02.avif", "$180"),
    prod(
      "hiking-boots",
      "Hiking Boots",
      "Waterproof, Vibram sole",
      "/dummy/trending03.avif",
      "$210",
    ),
    prod("canvas-slipons", "Canvas Slip-ons", "Everyday casual", "/dummy/trending04.avif", "$55"),
    prod(
      "oxford-dress-shoes",
      "Oxford Dress Shoes",
      "Goodyear welted",
      "/dummy/trending05.avif",
      "$260",
    ),
    prod(
      "trail-runners",
      "Trail Runners",
      "Rock-plate protection",
      "/dummy/trending06.avif",
      "$135",
    ),
  ],
  bags: [
    prod(
      "leather-tote",
      "Leather Tote",
      "Full-grain, laptop sleeve",
      "/dummy/new_arriavals01.avif",
      "$190",
    ),
    prod(
      "travel-duffel",
      "Travel Duffel",
      "45L, water-resistant",
      "/dummy/new_arriavals02.avif",
      "$110",
    ),
    prod(
      "daily-backpack",
      "Daily Backpack",
      "20L, USB pass-through",
      "/dummy/new_arriavals03.avif",
      "$85",
    ),
    prod(
      "crossbody-sling",
      "Crossbody Sling",
      "Anti-theft zip",
      "/dummy/new_arriavals04.avif",
      "$60",
    ),
    prod("weekender-bag", "Weekender Bag", "Waxed canvas", "/dummy/new_arriavals05.avif", "$150"),
    prod("evening-clutch", "Evening Clutch", "Satin finish", "/dummy/new_arriavals06.avif", "$75"),
  ],
  machinery: [
    prod(
      "cnc-mill",
      "CNC Milling Machine",
      "3-axis, 24k RPM",
      "/dummy/thumbnail_image01.avif",
      "$42,000",
    ),
    prod(
      "hydraulic-press",
      "Hydraulic Press",
      "100-ton capacity",
      "/dummy/thumbnail_image02.avif",
      "$18,500",
    ),
    prod(
      "industrial-lathe",
      "Industrial Lathe",
      "1.5m bed length",
      "/dummy/thumbnail_image03.avif",
      "$27,300",
    ),
    prod(
      "conveyor-system",
      "Conveyor System",
      "Modular, 10m",
      "/dummy/thumbnail_image04.avif",
      "$9,800",
    ),
    prod("arc-welder", "Arc Welder", "400A 3-phase", "/dummy/thumbnail_image05.avif", "$2,400"),
    prod(
      "electric-forklift",
      "Electric Forklift",
      "2.5-ton lift",
      "/dummy/thumbnail_image06.avif",
      "$31,000",
    ),
  ],
  jewelry: [
    prod(
      "diamond-ring",
      "Diamond Ring",
      "1ct, 18k gold band",
      "/dummy/spotlight_image01.avif",
      "$5,400",
    ),
    prod(
      "pearl-necklace",
      "Pearl Necklace",
      "Freshwater, 18in",
      "/dummy/spotlight_image02.avif",
      "$620",
    ),
    prod(
      "gold-bracelet",
      "Gold Bracelet",
      "22k, hand-engraved",
      "/dummy/spotlight_image03.avif",
      "$1,900",
    ),
    prod(
      "silver-earrings",
      "Silver Earrings",
      "Sterling, drop style",
      "/dummy/review_image01.avif",
      "$140",
    ),
    prod(
      "sapphire-pendant",
      "Sapphire Pendant",
      "Ceylon blue, 2ct",
      "/dummy/review_image02.avif",
      "$2,300",
    ),
    prod(
      "wedding-band",
      "Wedding Band",
      "Platinum, milgrain",
      "/dummy/review_image03.avif",
      "$980",
    ),
  ],
  furniture: [
    prod(
      "modular-sectional",
      "Modular Sectional",
      "5-seat, stain-proof",
      "/dummy/sofas.avif",
      "$2,100",
    ),
    prod(
      "oak-dining-table",
      "Oak Dining Table",
      "Seats 8, solid oak",
      "/dummy/tables.avif",
      "$1,450",
    ),
    prod("platform-bed", "Platform Bed", "Queen, upholstered", "/dummy/beds.avif", "$890"),
    prod("tall-bookshelf", "Tall Bookshelf", "6-tier oak", "/dummy/cabinets.avif", "$420"),
    prod(
      "accent-armchair",
      "Accent Armchair",
      "Velvet upholstery",
      "/dummy/living_room_chair.avif",
      "$540",
    ),
    prod(
      "arc-floor-lamp",
      "Arc Floor Lamp",
      "Brass, marble base",
      "/dummy/other_furniture.avif",
      "$180",
    ),
  ],

  // --- Furniture children ---
  "outdoor-furniture": [
    prod(
      "patio-dining-set",
      "Patio Dining Set",
      "Teak, 6-seat",
      "/dummy/outdoor_furniture.avif",
      "$1,800",
    ),
    prod(
      "cotton-hammock",
      "Cotton Hammock",
      "Double, with stand",
      "/dummy/thumbnail_image07.avif",
      "$130",
    ),
    prod(
      "sun-lounger",
      "Sun Lounger",
      "Reclining, weatherproof",
      "/dummy/chaise_lounge.avif",
      "$260",
    ),
    prod(
      "steel-fire-pit",
      "Steel Fire Pit",
      "36in, spark screen",
      "/dummy/thumbnail_image08.avif",
      "$190",
    ),
    prod(
      "garden-bench",
      "Garden Bench",
      "Cast iron + wood",
      "/dummy/thumbnail_image09.avif",
      "$240",
    ),
    prod(
      "cantilever-umbrella",
      "Cantilever Umbrella",
      "10ft, UV-coated",
      "/dummy/thumbnail_image10.avif",
      "$170",
    ),
  ],
  "home-furniture": [
    prod("three-seater-sofa", "3-Seater Sofa", "Linen blend", "/dummy/sofas.avif", "$1,200"),
    prod("king-bed-frame", "King Bed Frame", "Wingback headboard", "/dummy/beds.avif", "$1,050"),
    prod("lift-top-coffee-table", "Coffee Table", "Walnut, lift-top", "/dummy/tables.avif", "$380"),
    prod("tv-console", "TV Console", "70in, cable management", "/dummy/cabinets.avif", "$460"),
    prod(
      "bar-stool-set",
      "Bar Stool Set",
      "Set of 2, swivel",
      "/dummy/stools_and_ottomans.avif",
      "$220",
    ),
    prod("vanity-desk", "Vanity Desk", "LED mirror included", "/dummy/vanity.avif", "$340"),
  ],
  "commercial-furniture": [
    prod(
      "conference-table",
      "Conference Table",
      "12-seat, cable trough",
      "/dummy/tables.avif",
      "$2,400",
    ),
    prod(
      "reception-desk",
      "Reception Desk",
      "Laminate, LED front",
      "/dummy/commercial_furniture.avif",
      "$1,600",
    ),
    prod(
      "task-chair-10pack",
      "Task Chair (10-pack)",
      "Mesh, ergonomic",
      "/dummy/office_chair.avif",
      "$1,900",
    ),
    prod(
      "waiting-bench",
      "Waiting Room Bench",
      "4-seat, steel",
      "/dummy/stacking_chair.avif",
      "$720",
    ),
    prod("filing-cabinet", "Filing Cabinet", "4-drawer, locking", "/dummy/cabinets.avif", "$310"),
    prod(
      "office-partition",
      "Office Partition",
      "Acoustic, 4ft",
      "/dummy/other_furniture.avif",
      "$280",
    ),
  ],
  "kids-furniture": [
    prod("bunk-bed", "Bunk Bed", "Twin over twin, ladder", "/dummy/beds.avif", "$640"),
    prod(
      "toy-storage-cubbies",
      "Toy Storage Cubbies",
      "9-bin organizer",
      "/dummy/cabinets.avif",
      "$130",
    ),
    prod("kids-study-desk", "Kids Study Desk", "Height-adjustable", "/dummy/tables.avif", "$180"),
    prod("play-table", "Play Table", "Activity surface", "/dummy/kid's_furniture.avif", "$150"),
    prod("toddler-chair-set", "Toddler Chair Set", "Set of 2", "/dummy/dining_chair.avif", "$90"),
    prod("kids-bookcase", "Kids Bookcase", "Rounded edges", "/dummy/furniture_parts.avif", "$120"),
  ],
  "furniture-hardware": [
    prod(
      "drawer-slides",
      "Soft-close Drawer Slides",
      "18in, pair",
      "/dummy/furniture_hardware.avif",
      "$24",
    ),
    prod(
      "concealed-hinges",
      "Concealed Hinges",
      "Pack of 20",
      "/dummy/thumbnail_image11.avif",
      "$38",
    ),
    prod(
      "brushed-handles",
      "Brushed Handles",
      "10-pack, brass",
      "/dummy/thumbnail_image12.avif",
      "$45",
    ),
    prod(
      "leg-levelers",
      "Adjustable Leg Levelers",
      "Set of 4",
      "/dummy/furniture_parts.avif",
      "$16",
    ),
    prod(
      "locking-casters",
      "Locking Casters",
      "Set of 4, 2in",
      "/dummy/thumbnail_image01.avif",
      "$22",
    ),
    prod("l-brackets", "L-Brackets", "Heavy-duty, 8-pack", "/dummy/thumbnail_image02.avif", "$19"),
  ],
  "furniture-parts": [
    prod(
      "sofa-legs",
      "Replacement Sofa Legs",
      "Wood, set of 4",
      "/dummy/furniture_parts.avif",
      "$30",
    ),
    prod(
      "chair-cushion-insert",
      "Chair Cushion Insert",
      "High-density foam",
      "/dummy/stools_and_ottomans.avif",
      "$28",
    ),
    prod(
      "solid-wood-tabletop",
      "Solid Wood Tabletop",
      "Unfinished oak",
      "/dummy/tables.avif",
      "$160",
    ),
    prod("bed-slat-kit", "Bed Slat Kit", "Queen, reinforced", "/dummy/beds.avif", "$70"),
    prod(
      "dovetail-drawer-box",
      "Dovetail Drawer Box",
      "Pre-assembled",
      "/dummy/cabinets.avif",
      "$48",
    ),
    prod(
      "furniture-glides",
      "Furniture Glides",
      "Felt, 16-pack",
      "/dummy/thumbnail_image03.avif",
      "$12",
    ),
  ],
  "furniture-accessories": [
    prod(
      "throw-pillow-set",
      "Throw Pillow Set",
      "Set of 4, washable",
      "/dummy/furniture_accessories.avif",
      "$50",
    ),
    prod(
      "wool-area-rug",
      "Wool Area Rug",
      "8x10, hand-tufted",
      "/dummy/thumbnail_image04.avif",
      "$320",
    ),
    prod(
      "linen-table-runner",
      "Linen Table Runner",
      "72in",
      "/dummy/thumbnail_image05.avif",
      "$26",
    ),
    prod(
      "woven-storage-baskets",
      "Woven Storage Baskets",
      "Set of 3",
      "/dummy/thumbnail_image06.avif",
      "$42",
    ),
    prod("sofa-slipcover", "Sofa Slipcover", "Stretch, 3-seat", "/dummy/sofas.avif", "$65"),
    prod("marble-coasters", "Marble Coasters", "Set of 6", "/dummy/thumbnail_image07.avif", "$24"),
  ],
  "other-furniture": [
    prod("room-divider", "Room Divider", "4-panel, bamboo", "/dummy/other_furniture.avif", "$160"),
    prod("shoe-rack", "Shoe Rack", "5-tier, metal", "/dummy/thumbnail_image08.avif", "$55"),
    prod(
      "floating-wall-shelves",
      "Floating Wall Shelves",
      "Set of 3",
      "/dummy/thumbnail_image09.avif",
      "$40",
    ),
    prod("coat-stand", "Coat Stand", "Freestanding, wood", "/dummy/coat_racks.avif", "$90"),
    prod(
      "magazine-rack",
      "Magazine Rack",
      "Mid-century walnut",
      "/dummy/thumbnail_image10.avif",
      "$48",
    ),
    prod(
      "plant-stand-set",
      "Plant Stand Set",
      "Tiered, set of 2",
      "/dummy/thumbnail_image11.avif",
      "$58",
    ),
  ],

  // --- Home-furniture children ---
  sofas: [
    prod("chesterfield-sofa", "Chesterfield Sofa", "Tufted leather", "/dummy/sofas.avif", "$1,900"),
    prod(
      "velvet-loveseat",
      "Velvet Loveseat",
      "2-seat, blush",
      "/dummy/thumbnail_image01.avif",
      "$780",
    ),
    prod(
      "sleeper-sofa",
      "Sleeper Sofa",
      "Queen pull-out",
      "/dummy/thumbnail_image02.avif",
      "$1,150",
    ),
    prod(
      "l-sectional",
      "L-Shaped Sectional",
      "Reversible chaise",
      "/dummy/thumbnail_image03.avif",
      "$2,000",
    ),
    prod(
      "convertible-futon",
      "Convertible Futon",
      "Split-back",
      "/dummy/thumbnail_image04.avif",
      "$420",
    ),
    prod(
      "reclining-sofa",
      "Reclining Sofa",
      "Power, 3-seat",
      "/dummy/thumbnail_image05.avif",
      "$1,600",
    ),
  ],
  beds: [
    prod("canopy-bed", "Canopy Bed", "Four-poster, queen", "/dummy/beds.avif", "$1,300"),
    prod("storage-bed", "Storage Bed", "6 drawers, king", "/dummy/thumbnail_image06.avif", "$980"),
    prod("daybed-trundle", "Daybed with Trundle", "Twin", "/dummy/thumbnail_image07.avif", "$560"),
    prod(
      "adjustable-base",
      "Adjustable Bed Base",
      "Zero-gravity, king",
      "/dummy/thumbnail_image08.avif",
      "$1,100",
    ),
    prod(
      "murphy-bed",
      "Murphy Wall Bed",
      "Queen, cabinet",
      "/dummy/thumbnail_image09.avif",
      "$1,750",
    ),
    prod(
      "metal-bed-frame",
      "Metal Bed Frame",
      "Full, no box spring",
      "/dummy/thumbnail_image10.avif",
      "$260",
    ),
  ],
  chairs: [
    prod(
      "boucle-accent-chair",
      "Accent Chair",
      "Boucle, swivel",
      "/dummy/living_room_chair.avif",
      "$480",
    ),
    prod(
      "ergonomic-office-chair",
      "Ergonomic Office Chair",
      "Mesh, lumbar",
      "/dummy/office_chair.avif",
      "$540",
    ),
    prod(
      "rgb-gaming-chair",
      "Gaming Chair",
      "Racing style, RGB",
      "/dummy/gaming_chair.avif",
      "$320",
    ),
    prod("dining-chair-set-4", "Dining Chair Set", "Set of 4", "/dummy/dining_chair.avif", "$440"),
    prod("power-recliner-chair", "Power Recliner", "Heated, USB", "/dummy/recliner.avif", "$720"),
    prod("tufted-chaise", "Chaise Lounge", "Tufted velvet", "/dummy/chaise_lounge.avif", "$610"),
  ],
  "coat-racks": [
    prod(
      "freestanding-coat-rack",
      "Freestanding Coat Rack",
      "8-hook, walnut",
      "/dummy/coat_racks.avif",
      "$90",
    ),
    prod(
      "wall-coat-rack",
      "Wall-mounted Rack",
      "6-hook, brass",
      "/dummy/thumbnail_image11.avif",
      "$45",
    ),
    prod(
      "hall-tree-bench",
      "Hall Tree with Bench",
      "Storage seat",
      "/dummy/thumbnail_image12.avif",
      "$210",
    ),
    prod(
      "tree-style-rack",
      "Tree-style Rack",
      "Rotating top",
      "/dummy/thumbnail_image01.avif",
      "$70",
    ),
    prod(
      "entryway-organizer",
      "Entryway Organizer",
      "Hooks + shelf",
      "/dummy/thumbnail_image02.avif",
      "$120",
    ),
    prod(
      "industrial-pipe-rack",
      "Industrial Pipe Rack",
      "Black steel",
      "/dummy/thumbnail_image03.avif",
      "$85",
    ),
  ],
  "stools-and-ottomans": [
    prod(
      "storage-ottoman",
      "Storage Ottoman",
      "Lift-top, linen",
      "/dummy/stools_and_ottomans.avif",
      "$140",
    ),
    prod(
      "swivel-bar-stool",
      "Swivel Bar Stool",
      "Adjustable height",
      "/dummy/thumbnail_image04.avif",
      "$95",
    ),
    prod("knitted-pouf", "Knitted Pouf", "Round, cotton", "/dummy/thumbnail_image05.avif", "$60"),
    prod(
      "footrest-ottoman",
      "Footrest Ottoman",
      "Tufted velvet",
      "/dummy/thumbnail_image06.avif",
      "$110",
    ),
    prod(
      "counter-stool-set",
      "Counter Stool Set",
      "Set of 2, wood",
      "/dummy/thumbnail_image07.avif",
      "$180",
    ),
    prod(
      "vanity-stool",
      "Vanity Stool",
      "Upholstered, gold legs",
      "/dummy/thumbnail_image08.avif",
      "$85",
    ),
  ],
  tables: [
    prod(
      "extendable-dining-table",
      "Extendable Dining Table",
      "Seats 6-10",
      "/dummy/tables.avif",
      "$1,200",
    ),
    prod(
      "console-table",
      "Console Table",
      "Narrow, entryway",
      "/dummy/thumbnail_image09.avif",
      "$290",
    ),
    prod(
      "marble-side-tables",
      "Side Table",
      "Marble top, set of 2",
      "/dummy/thumbnail_image10.avif",
      "$220",
    ),
    prod(
      "writing-desk",
      "Writing Desk",
      "Solid oak, drawer",
      "/dummy/thumbnail_image11.avif",
      "$480",
    ),
    prod("nesting-tables", "Nesting Tables", "Set of 3", "/dummy/thumbnail_image12.avif", "$160"),
    prod(
      "bistro-table",
      "Bistro Table",
      "Round, cafe style",
      "/dummy/thumbnail_image01.avif",
      "$130",
    ),
  ],
  vanity: [
    prod(
      "makeup-vanity-set",
      "Makeup Vanity Set",
      "LED mirror, stool",
      "/dummy/vanity.avif",
      "$360",
    ),
    prod(
      "bathroom-vanity",
      "Bathroom Vanity",
      "48in, double sink",
      "/dummy/thumbnail_image02.avif",
      "$720",
    ),
    prod(
      "floating-vanity",
      "Floating Vanity",
      "Wall-mounted, 36in",
      "/dummy/thumbnail_image03.avif",
      "$540",
    ),
    prod("corner-vanity", "Corner Vanity", "Space-saving", "/dummy/thumbnail_image04.avif", "$410"),
    prod(
      "hollywood-vanity-mirror",
      "Hollywood Vanity Mirror",
      "12 dimmable bulbs",
      "/dummy/thumbnail_image05.avif",
      "$150",
    ),
    prod(
      "trifold-vanity",
      "Tri-fold Vanity",
      "Adjustable mirrors",
      "/dummy/thumbnail_image06.avif",
      "$280",
    ),
  ],
  cabinets: [
    prod(
      "kitchen-cabinet-set",
      "Kitchen Cabinet Set",
      "Shaker, 10-piece",
      "/dummy/cabinets.avif",
      "$3,200",
    ),
    prod(
      "glass-display-cabinet",
      "Glass Display Cabinet",
      "LED-lit",
      "/dummy/thumbnail_image07.avif",
      "$640",
    ),
    prod(
      "storage-cabinet",
      "Storage Cabinet",
      "2-door, adjustable",
      "/dummy/thumbnail_image08.avif",
      "$290",
    ),
    prod(
      "medicine-cabinet",
      "Medicine Cabinet",
      "Mirrored, recessed",
      "/dummy/thumbnail_image09.avif",
      "$140",
    ),
    prod(
      "sideboard-buffet",
      "Sideboard Buffet",
      "3-door, walnut",
      "/dummy/thumbnail_image10.avif",
      "$580",
    ),
    prod(
      "shoe-cabinet",
      "Shoe Cabinet",
      "Tilt-out, 3-tier",
      "/dummy/thumbnail_image11.avif",
      "$170",
    ),
  ],

  // --- Chairs children ---
  "living-room-chair": [
    prod(
      "wingback-armchair",
      "Wingback Armchair",
      "Tufted, nailhead trim",
      "/dummy/living_room_chair.avif",
      "$520",
    ),
    prod(
      "leather-club-chair",
      "Leather Club Chair",
      "Distressed brown",
      "/dummy/chair_charcoal_black.avif",
      "$680",
    ),
    prod(
      "swivel-accent-chair",
      "Swivel Accent Chair",
      "Boucle, 360°",
      "/dummy/chair_sea_blue.avif",
      "$440",
    ),
    prod(
      "barrel-chair",
      "Barrel Chair",
      "Curved back, velvet",
      "/dummy/chair_royal_purple.avif",
      "$390",
    ),
    prod(
      "slipper-chair",
      "Slipper Chair",
      "Armless, compact",
      "/dummy/chair_raspberry_red.avif",
      "$260",
    ),
    prod(
      "reading-chair-ottoman",
      "Reading Chair + Ottoman",
      "Mid-century",
      "/dummy/chair_raspberry_red02.avif",
      "$610",
    ),
  ],
  "gaming-chair": [
    prod(
      "racing-pro-chair",
      "Racing Pro Chair",
      "Reclining, RGB",
      "/dummy/gaming_chair.avif",
      "$360",
    ),
    prod(
      "ergo-gaming-chair",
      "Ergonomic Gaming Chair",
      "4D armrests",
      "/dummy/thumbnail_image01.avif",
      "$420",
    ),
    prod(
      "floor-gaming-chair",
      "Floor Gaming Chair",
      "Foldable, padded",
      "/dummy/thumbnail_image02.avif",
      "$130",
    ),
    prod(
      "budget-racer-chair",
      "Budget Racer Chair",
      "PU leather",
      "/dummy/thumbnail_image03.avif",
      "$180",
    ),
    prod(
      "pedestal-gaming-chair",
      "Pedestal Gaming Chair",
      "Built-in speakers",
      "/dummy/thumbnail_image04.avif",
      "$290",
    ),
    prod(
      "gaming-chair-footrest",
      "Gaming Chair w/ Footrest",
      "Recline 165°",
      "/dummy/thumbnail_image05.avif",
      "$250",
    ),
  ],
  "dining-chair": [
    prod(
      "upholstered-dining-chairs",
      "Upholstered Dining Chairs",
      "Set of 4",
      "/dummy/dining_chair.avif",
      "$440",
    ),
    prod(
      "wood-dining-chairs",
      "Solid Wood Dining Chairs",
      "Set of 2",
      "/dummy/thumbnail_image06.avif",
      "$220",
    ),
    prod(
      "velvet-dining-chairs",
      "Velvet Dining Chairs",
      "Gold legs, set of 2",
      "/dummy/thumbnail_image07.avif",
      "$260",
    ),
    prod(
      "dining-bench",
      "Dining Bench",
      "Upholstered, 48in",
      "/dummy/thumbnail_image08.avif",
      "$190",
    ),
    prod(
      "windsor-chairs",
      "Windsor Chairs",
      "Classic, set of 4",
      "/dummy/thumbnail_image09.avif",
      "$380",
    ),
    prod(
      "ghost-chairs",
      "Acrylic Ghost Chairs",
      "Set of 4",
      "/dummy/thumbnail_image10.avif",
      "$300",
    ),
  ],
  "office-chair": [
    prod(
      "ergonomic-mesh-chair",
      "Ergonomic Mesh Chair",
      "Lumbar, headrest",
      "/dummy/office_chair.avif",
      "$540",
    ),
    prod(
      "executive-leather-chair",
      "Executive Leather Chair",
      "High-back",
      "/dummy/thumbnail_image11.avif",
      "$620",
    ),
    prod(
      "drafting-stool",
      "Drafting Stool",
      "Foot ring, tall",
      "/dummy/thumbnail_image12.avif",
      "$230",
    ),
    prod(
      "kneeling-chair",
      "Kneeling Chair",
      "Posture support",
      "/dummy/thumbnail_image01.avif",
      "$160",
    ),
    prod(
      "conference-chairs",
      "Conference Chairs",
      "Set of 2",
      "/dummy/thumbnail_image02.avif",
      "$340",
    ),
    prod(
      "compact-task-chair",
      "Compact Task Chair",
      "Armless, swivel",
      "/dummy/thumbnail_image03.avif",
      "$120",
    ),
  ],
  "chaise-lounge": [
    prod(
      "velvet-chaise-lounge",
      "Velvet Chaise Lounge",
      "Tufted, gold legs",
      "/dummy/chaise_lounge.avif",
      "$610",
    ),
    prod(
      "outdoor-chaise",
      "Outdoor Chaise",
      "Weatherproof wicker",
      "/dummy/thumbnail_image04.avif",
      "$380",
    ),
    prod(
      "double-chaise",
      "Double Chaise",
      "Indoor, linen",
      "/dummy/thumbnail_image05.avif",
      "$890",
    ),
    prod(
      "leather-chaise",
      "Leather Chaise",
      "Mid-century",
      "/dummy/thumbnail_image06.avif",
      "$720",
    ),
    prod(
      "storage-chaise",
      "Storage Chaise",
      "Hidden compartment",
      "/dummy/thumbnail_image07.avif",
      "$540",
    ),
    prod(
      "fainting-couch",
      "Fainting Couch",
      "Victorian style",
      "/dummy/thumbnail_image08.avif",
      "$660",
    ),
  ],
  recliner: [
    prod("power-recliner", "Power Recliner", "Heated, massage", "/dummy/recliner.avif", "$820"),
    prod(
      "rocker-recliner",
      "Rocker Recliner",
      "Swivel base",
      "/dummy/thumbnail_image09.avif",
      "$560",
    ),
    prod(
      "wall-hugger-recliner",
      "Wall-hugger Recliner",
      "Space-saving",
      "/dummy/thumbnail_image10.avif",
      "$480",
    ),
    prod(
      "lift-recliner",
      "Lift Recliner",
      "Assisted stand",
      "/dummy/thumbnail_image11.avif",
      "$740",
    ),
    prod(
      "leather-recliner",
      "Leather Recliner",
      "Top-grain",
      "/dummy/thumbnail_image12.avif",
      "$690",
    ),
    prod("recliner-set", "Recliner Set", "2 + console", "/dummy/thumbnail_image01.avif", "$1,400"),
  ],
  "stacking-chair": [
    prod(
      "plastic-stacking-chairs",
      "Plastic Stacking Chairs",
      "Set of 10",
      "/dummy/stacking_chair.avif",
      "$250",
    ),
    prod(
      "metal-stacking-chairs",
      "Metal Stacking Chairs",
      "Set of 4",
      "/dummy/thumbnail_image02.avif",
      "$180",
    ),
    // Leads the "Popular in Stacking Chair" rail (window starts at pool index 2).
    prod(
      "lv-folding-chair",
      "Louis Vuitton Folding Metal Living Room Chair(Finish Color - Red, Pre-assembled)",
      "Pre-assembled, Red",
      "/dummy/chair_raspberry_red.avif",
      "$753.80",
    ),
    prod(
      "padded-stacking-chairs",
      "Padded Stacking Chairs",
      "Set of 6",
      "/dummy/thumbnail_image03.avif",
      "$320",
    ),
    prod(
      "event-chairs",
      "Event Chairs",
      "Folding, set of 20",
      "/dummy/thumbnail_image04.avif",
      "$400",
    ),
    prod(
      "church-chairs",
      "Church Chairs",
      "Linkable, set of 4",
      "/dummy/thumbnail_image05.avif",
      "$260",
    ),
    prod(
      "cafe-stacking-stools",
      "Cafe Stacking Stools",
      "Set of 4",
      "/dummy/thumbnail_image06.avif",
      "$210",
    ),
  ],
  "massage-chair": [
    prod(
      "full-body-massage-chair",
      "Full-body Massage Chair",
      "Zero-gravity, heat",
      "/dummy/massage_chair.avif",
      "$2,400",
    ),
    prod(
      "shiatsu-massage-chair",
      "Shiatsu Massage Chair",
      "3D rollers",
      "/dummy/thumbnail_image07.avif",
      "$1,800",
    ),
    prod(
      "compact-massage-recliner",
      "Compact Massage Recliner",
      "Space-saving",
      "/dummy/thumbnail_image08.avif",
      "$1,200",
    ),
    prod(
      "office-massage-chair",
      "Office Massage Chair",
      "Cushion overlay",
      "/dummy/thumbnail_image09.avif",
      "$320",
    ),
    prod(
      "recliner-foot-massager",
      "Recliner + Foot Massager",
      "Calf rollers",
      "/dummy/thumbnail_image10.avif",
      "$1,500",
    ),
    prod(
      "luxury-massage-throne",
      "Luxury Massage Throne",
      "4D, Bluetooth",
      "/dummy/thumbnail_image11.avif",
      "$4,200",
    ),
  ],
};

// slug -> 3 themed rails. getCategory falls back to MOCK_LEAF_RAILS for any
// slug missing a pool (none today, but keeps the catch-all route safe).
export const MOCK_CATEGORY_RAILS: Record<string, ProductRail[]> = Object.fromEntries(
  Object.entries(CATEGORY_PRODUCT_POOLS).map(([slug, pool]) => [
    slug,
    railsForCategory(slug, MOCK_CATEGORIES[slug]?.name ?? slug, pool),
  ]),
);

export const MOCK_PATHWAYS: Pathway[] = [
  {
    slug: "louis-vuitton-collection",
    title: "Louis Vuitton Collection",
    subtitle: "Build the full seasonal look",
    imageSrc: "/dummy/pathways_1.avif",
    overlayLabel: "Louis Vuitton Collection",
    items: [
      {
        id: "shirt",
        name: "Tailored Shirt",
        categoryLabel: "Clothes",
        imageSrc: "/dummy/thumbnail_image03.avif",
        price: "$680",
        href: "/store/clothes",
      },
      {
        id: "trousers",
        name: "Pleated Trousers",
        categoryLabel: "Clothes",
        imageSrc: "/dummy/thumbnail_image04.avif",
        price: "$540",
        href: "/store/clothes",
      },
      {
        id: "boots",
        name: "Leather Boots",
        categoryLabel: "Footwear",
        imageSrc: "/dummy/thumbnail_image05.avif",
        price: "$1,120",
        href: "/store/clothes",
      },
      {
        id: "shoulder-bag",
        name: "Shoulder Bag",
        categoryLabel: "Accessories",
        imageSrc: "/dummy/thumbnail_image06.avif",
        price: "$1,910",
        href: "/store/accessories",
      },
      {
        id: "watch",
        name: "Dress Watch",
        categoryLabel: "Accessories",
        imageSrc: "/dummy/thumbnail_image07.avif",
        price: "$2,300",
        href: "/store/accessories",
      },
    ],
  },
  {
    slug: "p-designs",
    title: "P Designs",
    subtitle: "Everything a design studio ships with",
    imageSrc: "/dummy/pathways_2.avif",
    items: [
      {
        id: "design-system",
        name: "Design System License",
        categoryLabel: "Software",
        imageSrc: "/dummy/thumbnail_image01.avif",
        price: "$600",
        href: "/store/clothes",
      },
      {
        id: "ui-kit",
        name: "Mobile UI Kit",
        categoryLabel: "Templates",
        imageSrc: "/dummy/thumbnail_image02.avif",
        price: "$300",
        href: "/store/clothes",
      },
      {
        id: "icon-pack",
        name: "Icon Pack Pro",
        categoryLabel: "Assets",
        imageSrc: "/dummy/thumbnail_image03.avif",
        price: "$120",
        href: "/store/clothes",
      },
      {
        id: "handoff-tool",
        name: "Dev Handoff Tool",
        categoryLabel: "Software",
        imageSrc: "/dummy/thumbnail_image04.avif",
        price: "$180",
        href: "/store/clothes",
      },
    ],
  },
  {
    slug: "steel-nail",
    title: "Steel Nail",
    subtitle: "Carbon steel concrete masonry nail",
    imageSrc: "/dummy/pathways_3.avif",
    items: [
      {
        id: "masonry-nail",
        name: "Masonry Nail Box",
        categoryLabel: "Fasteners",
        imageSrc: "/dummy/thumbnail_image05.avif",
        price: "$3 / box",
        href: "/store/accessories",
      },
      {
        id: "nail-gun",
        name: "Pneumatic Nail Gun",
        categoryLabel: "Tools",
        imageSrc: "/dummy/thumbnail_image06.avif",
        price: "$240",
        href: "/store/accessories",
      },
      {
        id: "compressor",
        name: "Air Compressor",
        categoryLabel: "Tools",
        imageSrc: "/dummy/thumbnail_image07.avif",
        price: "$410",
        href: "/store/accessories",
      },
    ],
  },
  {
    slug: "bomber-drone-classic",
    title: "Bomber Drone Classic",
    subtitle: "Affordable drone for war",
    imageSrc: "/dummy/pathways_4.avif",
    items: [
      {
        id: "drone-frame",
        name: "Carbon Drone Frame",
        categoryLabel: "Airframe",
        imageSrc: "/dummy/thumbnail_image08.avif",
        price: "$2,100",
        href: "/store/accessories",
      },
      {
        id: "battery-pack",
        name: "High-density Battery Pack",
        categoryLabel: "Power",
        imageSrc: "/dummy/thumbnail_image09.avif",
        price: "$1,800",
        href: "/store/accessories",
      },
      {
        id: "controller",
        name: "Ground Controller",
        categoryLabel: "Avionics",
        imageSrc: "/dummy/thumbnail_image10.avif",
        price: "$3,400",
        href: "/store/accessories",
      },
      {
        id: "camera-module",
        name: "Thermal Camera Module",
        categoryLabel: "Payload",
        imageSrc: "/dummy/thumbnail_image11.avif",
        price: "$5,100",
        href: "/store/accessories",
      },
    ],
  },
  {
    slug: "steel-roll",
    title: "Steel Roll",
    subtitle: "Tata Cold Steel Roll",
    imageSrc: "/dummy/pathways_5.avif",
    items: [
      {
        id: "cold-roll",
        name: "Cold-rolled Coil",
        categoryLabel: "Raw Material",
        imageSrc: "/dummy/thumbnail_image12.avif",
        price: "$890 / ton",
        href: "/store/furniture",
      },
      {
        id: "galvanized-sheet",
        name: "Galvanized Sheet",
        categoryLabel: "Raw Material",
        imageSrc: "/dummy/thumbnail_image01.avif",
        price: "$960 / ton",
        href: "/store/furniture",
      },
      {
        id: "slitting-service",
        name: "Slitting Service",
        categoryLabel: "Processing",
        imageSrc: "/dummy/thumbnail_image02.avif",
        price: "$40 / ton",
        href: "/store/furniture",
      },
    ],
  },
];

const MOCK_B2B_LINKS: B2BLink[] = [
  {
    id: "all-categories",
    label: "All Categories",
    iconSrc: "/icons/category_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/categories",
  },
  {
    id: "request-for-quotation",
    label: "Request for Quotation",
    iconSrc: "/icons/request_quote_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/rfq",
  },
  {
    id: "logistic-services",
    label: "Logistic Services",
    iconSrc: "/icons/directions_boat_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/logistics",
  },
  {
    id: "factories-worldwide",
    label: "Factories Worldwide",
    iconSrc: "/icons/factory_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/factories",
  },
  {
    id: "business-forum",
    label: "Business Forum",
    iconSrc: "/icons/forum_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/forum",
  },
  {
    id: "find-cofounder",
    label: "Find Cofounder",
    iconSrc: "/icons/group_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg",
    href: "/store/find-cofounder",
  },
];

export const MOCK_STORE_HOME: StoreHome = {
  hero: HERO_SLIDES,
  rootCategories: ROOT_CATEGORY_SLUGS.map((slug, i) => ({
    ...MOCK_CATEGORIES[slug],
    hoverBg: hoverAt(i),
  })),
  pathways: MOCK_PATHWAYS.map((p, i) => ({ ...p, hoverBg: hoverAt(i) })),
  b2bLinks: MOCK_B2B_LINKS,
  rails: MOCK_RAILS,
};
